#!/usr/bin/env bash
# Explicit immutable-release deploy — requires manual invocation and explicit ASRSUB_IMAGE.
# This is intentionally separate from build.sh to prevent unintended state changes.
# Fails closed if the release image is not set; never builds at deploy time (--no-build).
# Review DEPLOY.md before running.
set -euo pipefail
cd "$(dirname "$0")"

RELEASE_ENV=".release.env"

# Load release descriptor if present (non-secret). CLI / env var takes precedence.
if [[ -f "${RELEASE_ENV}" ]]; then
  # shellcheck disable=SC1090
  set -a
  # Only allowlist ASRSUB_IMAGE/GIT_SHA/BUILD_TIME from descriptor to avoid env injection
  # shellcheck disable=SC2046
  # Use simple source; descriptor is generated by build.sh and contains no secrets.
  source "${RELEASE_ENV}"
  set +a
fi

# Allow explicit first arg as image override: ./deploy.sh asrsub:<sha>
if [[ -n "${1:-}" ]]; then
  ASRSUB_IMAGE="$1"
fi

echo "=== ASRSub Deploy (explicit, immutable) ==="
echo "This will restart the stack with an explicit immutable image. Data mounts are retained; ensure secrets are present."
echo "  Release image: \${ASRSUB_IMAGE:?set ASRSUB_IMAGE to release tag (e.g. asrsub:<git-sha>) or ensure ${RELEASE_ENV} exists}"
echo "  Secret file: \${CONTROL_API_KEY_FILE_HOST:-/home/user/.config/asr-pipeline/secrets/control_api_key} -> /run/secrets/control_api_key"
echo "  Config: /home/user/.config/asr-pipeline/pipeline.env (non-control settings only)"
echo "  State: local btrfs at /home/user/.config/asr-pipeline (see HEALTH.md)"
echo "  Media: NFS /mnt/nas/share/media (must be mounted)"
echo "  Release descriptor: ${RELEASE_ENV} / release.json (non-secret)"
echo ""

# Fail closed: require explicit immutable image (full 40-char SHA tag).
if [[ -z "${ASRSUB_IMAGE:-}" ]]; then
  echo "ERROR: ASRSUB_IMAGE must be set to immutable release tag (e.g. asrsub:<git-sha>)" >&2
  echo "  Hint: run ./build.sh to generate ${RELEASE_ENV} with ASRSUB_IMAGE=asrsub:<git-sha>, then re-run deploy, or export ASRSUB_IMAGE explicitly." >&2
  echo "  Current: ASRSUB_IMAGE is unset/empty; docker-compose.yml will also fail closed via \${ASRSUB_IMAGE:?}." >&2
  exit 1
fi
if [[ ! "${ASRSUB_IMAGE}" =~ ^asrsub:[0-9a-f]{40}$ ]]; then
  echo "ERROR: ASRSUB_IMAGE must be immutable asrsub:<full-40-char-git-sha> (got '${ASRSUB_IMAGE}')" >&2
  echo "  Expected: asrsub:0123456789abcdef... (40 hex chars)" >&2
  exit 1
fi

# Optional: verify image exists locally before attempting up
if ! docker image inspect "${ASRSUB_IMAGE}" >/dev/null 2>&1; then
  echo "ERROR: Release image not found locally: ${ASRSUB_IMAGE}" >&2
  echo "  Build it first: ./build.sh ${ASRSUB_IMAGE#asrsub:}" >&2
  exit 1
fi

read -p "Proceed with 'docker compose up -d --no-build' for ${ASRSUB_IMAGE}? (y/N) " ans
if [[ "$ans" != "y" && "$ans" != "Y" ]]; then
  echo "Aborted."
  exit 1
fi

# Verify secret file exists
SECRET_HOST="${CONTROL_API_KEY_FILE_HOST:-/home/user/.config/asr-pipeline/secrets/control_api_key}"
if [[ ! -f "$SECRET_HOST" ]]; then
  echo "ERROR: Secret file not found at $SECRET_HOST"
  echo "Create it with: mkdir -p \$(dirname \"$SECRET_HOST\") && chmod 600 \"\$SECRET_HOST\" && echo -n \"<key>\" > \"\$SECRET_HOST\""
  exit 1
fi

# Verify health prerequisites
echo "==> Health prerequisites (see HEALTH.md)"
if ! mountpoint -q /mnt/nas/share/media 2>/dev/null && ! grep -q " /mnt/nas/share/media " /proc/mounts 2>/dev/null; then
  echo "WARNING: NFS media mount /mnt/nas/share/media not detected; continue anyway? (y/N)"
  read -p "> " ans2
  if [[ "$ans2" != "y" && "$ans2" != "Y" ]]; then exit 1; fi
fi

echo "==> Starting stack (retains volumes, --no-build)"
# Use explicit env-file if present, otherwise rely on exported ASRSUB_IMAGE.
if [[ -f "${RELEASE_ENV}" ]]; then
  docker compose --env-file "${RELEASE_ENV}" up -d --no-build
else
  ASRSUB_IMAGE="${ASRSUB_IMAGE}" docker compose up -d --no-build
fi
echo ""
echo "==> Status"
docker compose ps
echo ""
echo "==> Health"
curl -sf http://127.0.0.1:8085/health || echo "health check failed (orchestrator may be starting)"
curl -sf http://127.0.0.1:8085/ready 2>/dev/null || echo "ready check: /ready not yet available (see HEALTH.md)"
