#!/usr/bin/env python3
"""Single-video subtitle quality test: ASR -> HY-MT1.5 7B merge-aware translate -> SRT.

The ASR backend follows the ASR_BACKEND env via orchestrator.asr_cues
dispatch: faster-whisper (pipeline/asr.py) by default, SenseVoice
(pipeline/sensevoice.py) with ASR_BACKEND=sensevoice.

Refactored for orchestrator v2: ASR via orchestrator.asr_cues (backend-
aware), translate via orchestrator._translate_merge_aware (chunk 10 + tail
completion + echo retry + per-line fallback + glossary REFs), SRT via
orchestrator.write_srt with proper HH:MM:SS,mmm timestamps and optional AI
header.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time

import orchestrator as o


def ffprobe_audio(video):
    p = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "a",
            "-show_entries",
            "stream=index,codec_name,channels",
            "-of",
            "json",
            video,
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if p.returncode != 0:
        raise RuntimeError(f"ffprobe failed: {p.stderr}")
    return json.loads(p.stdout).get("streams", [])


def extract_audio(video, stream_index, out_wav):
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-v",
            "error",
            "-i",
            video,
            "-map",
            f"0:{stream_index}",
            "-vn",
            "-ac",
            "1",
            "-ar",
            "16000",
            "-c:a",
            "pcm_s16le",
            out_wav,
        ],
        check=True,
        capture_output=True,
        timeout=600,
    )


def main(argv):
    ap = argparse.ArgumentParser(description="Single-video subtitle quality test")
    ap.add_argument("--video", required=True, help="input video path")
    ap.add_argument("--lang", default="id", choices=["id", "en"])
    ap.add_argument("--out", default=None, help="output SRT path")
    ap.add_argument(
        "--stream",
        type=int,
        default=0,
        help="audio stream index (0-based within audio streams)",
    )
    ap.add_argument("--whisper", default="large-v3-turbo", help="faster-whisper model")
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--compute", default="int8")
    ap.add_argument("--series", default=None, help="series title for glossary refs")
    ap.add_argument("--ai", action="store_true", help="write [AI-generated by ASRSub] header")
    args = ap.parse_args(argv)

    if not os.path.isfile(args.video):
        print(f"ERROR: video not found: {args.video}", file=sys.stderr)
        return 1

    streams = ffprobe_audio(args.video)
    if not streams:
        print(f"ERROR: no audio streams in {args.video}", file=sys.stderr)
        return 1
    if args.stream >= len(streams):
        avail = ", ".join(
            f"[{i}] {s.get('codec_name')} ch={s.get('channels')}"
            for i, s in enumerate(streams)
        )
        print(
            f"ERROR: stream {args.stream} out of range; available audio streams: {avail}",
            file=sys.stderr,
        )
        return 1

    out = args.out
    if not out:
        d = os.path.dirname(args.video)
        base = os.path.splitext(os.path.basename(args.video))[0]
        out = os.path.join(d, f"{base}.test.{args.lang}.srt")

    wav = f"/tmp/oneshot_{os.getpid()}.wav"
    t0 = time.time()
    try:
        sel = streams[args.stream]
        extract_audio(args.video, sel["index"], wav)

        os.environ["WHISPER_MODEL"] = args.whisper
        os.environ["WHISPER_DEVICE"] = args.device
        os.environ["WHISPER_COMPUTE"] = args.compute
        # Reset whichever backend ASR_BACKEND selects so a fresh model is
        # loaded (one_shot_test may run repeatedly in long-lived processes);
        # orchestrator.asr_cues does not reset models itself.
        if o.ASR_BACKEND == "sensevoice":
            from pipeline import sensevoice as _sv

            _sv.reset_model()
        else:
            import pipeline.asr as pasr

            pasr.reset_model()
        cues = o.asr_cues({}, wav, "ja")

        texts = [c["text"] for c in cues]
        sanitized = o.sanitize_lines(texts)
        guarded, _foreign = o.guard_foreign_lines(sanitized)
        cfg = {
            "TRANSLATE_BASE": "http://127.0.0.1:8011/v1",
            "TRANSLATE_MODEL": "HY-MT1.5-7B-Q4_K_M.gguf",
            "SDH_PLACEHOLDERS": list(o.DEFAULT_SDH_PLACEHOLDERS),
        }
        lang_name = o.LANG_NAMES.get(args.lang, args.lang)
        refs = o.pipeline_glossary.terminology_block(args.series) if args.series else ""
        groups = o._translate_merge_aware(cfg, guarded, lang_name, "oneshot", refs=refs)
        cues_out = []
        texts_out = []
        for s, e, t in groups:
            cues_out.append({"start": cues[s]["start"], "end": cues[e - 1]["end"]})
            texts_out.append(t)
        o.write_srt(cues_out, texts_out, out, header=o.AI_MARKER if args.ai else None)

        num_chunks = (len(guarded) + o.TRANSLATE_CHUNK - 1) // o.TRANSLATE_CHUNK
        total_chars = sum(len(t) for t in texts_out)
        elapsed_s = round(time.time() - t0, 1)

        cjk_re = re.compile(r"[\u3040-\u30ff\u3400-\u9fff]")
        srt_cjk = 0
        with open(out, encoding="utf-8") as fh:
            for line in fh:
                if (
                    cjk_re.search(line)
                    and "-->" not in line
                    and not line.strip().isdigit()
                ):
                    srt_cjk += 1

        print(f"num_cues: {len(cues_out)}")
        print(f"num_chunks_used: {num_chunks}")
        print(f"total_chars: {total_chars}")
        print(f"elapsed_s: {elapsed_s}")
        print(f"output_cjk_lines: {srt_cjk}")
        print(f"srt: {out}")
        return 0
    finally:
        try:
            os.remove(wav)
        except OSError:
            pass


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
