#!/usr/bin/env python3
"""AI subtitle pipeline orchestrator v2: wanted list -> faster-whisper ASR -> LLM translate -> Bazarr upload.

Self-looping daemon (flock guards single instance). Idempotent via JSONL state file.

v2 changes (rewrite track): faster-whisper large-v3-turbo int8 + Silero VAD
(replaces dead FunASR :9000), whisper-segment splitting to <=8s cues,
merge-aware 7B translation (chunk 10 + tail completion + echo retry +
per-line fallback), HY-MT1.5 official terminology-intervention glossary
(Technical Report 3.4), AI provenance as a real first SRT cue
("[AI-generated by ASRSub]", config AI_MARKER_CUE), on-disk {stem}.{lang}.srt
(no .ai suffix; Bazarr rewrites names via subliminal anyway),
config-driven SDH placeholders.
"""

import collections
import fcntl
import hashlib
import hmac
import json
import os
import re
import signal
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone

import requests
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pipeline import asr as pipeline_asr
from pipeline import glossary as pipeline_glossary

_LOG_LOCK = threading.Lock()
_LOG_RING = collections.deque(maxlen=25)

ENV_FILE = "/home/user/.config/asr-pipeline/pipeline.env"
STATE_FILE = os.environ.get("STATE_FILE", "/home/user/.config/asr-pipeline/state.jsonl")
ACTIONS_FILE = os.environ.get("ACTIONS_FILE", "/home/user/.config/asr-pipeline/actions.jsonl")
EXCLUSIONS_FILE = os.environ.get(
    "EXCLUSIONS_FILE", "/home/user/.config/asr-pipeline/exclusions.jsonl"
)

JELLYFIN_URL = os.environ.get("JELLYFIN_URL", "http://10.10.20.160:8096")
JELLYFIN_MEDIA_ROOT = os.environ.get("JELLYFIN_MEDIA_ROOT", "/media")

TRANSLATE_PROMPT = (
    "You are a professional anime subtitle translator. Translate the provided Japanese "
    "subtitle lines into {target_language}. Rules: (1) output ONLY a JSON array of strings, "
    "same count and order as input; (2) natural dialogue, keep honorifics and name suffixes "
    "(san/chan/kun); (3) each line <=42 characters; (4) do not add anything not in the "
    "source; (5) no timestamps, no numbering."
)

BATCH_SIZE = 20
TIMEOUT = 900
MODEL_FALLBACKS = [
    m.strip()
    for m in os.environ.get("TRANSLATE_FALLBACK_MODELS", "").split(",")
    if m.strip()
]
MAX_WORKERS = int(os.environ.get("MAX_TRANSLATE_WORKERS", "1"))
WAKE_EVENT = threading.Event()
WEBHOOK_PORT = int(os.environ.get("WEBHOOK_PORT", "8085"))
OVERRIDE_FILE = "/home/user/.config/asr-pipeline/config.overrides.json"
CONTROL_API_KEY = os.environ.get("CONTROL_API_KEY", "")
ASR_CACHE_DIR = os.environ.get(
    "ASR_CACHE_DIR",
    os.path.join(os.path.expanduser("~"), ".cache", "asr-pipeline", "asr"),
)

TRANSLATE_BASE = os.environ.get("TRANSLATE_BASE", "http://127.0.0.1:8011/v1")
TRANSLATE_MODEL = os.environ.get("TRANSLATE_MODEL", "HY-MT1.5-7B-Q4_K_M.gguf")
TRANSLATE_CHUNK = int(os.environ.get("TRANSLATE_CHUNK", "10"))
LANG_NAMES = {"id": "Indonesian", "en": "English"}
KANA_RE = re.compile(r"[\u3040-\u30ff]")
HANZI_RE = re.compile(r"[\u3400-\u9fff]")
LATIN_RE = re.compile(r"[A-Za-z]")
CTX_OVERFLOW = "__CTX_OVERFLOW__"
HY_STOP_TOKENS = ["<｜hy_place▁holder▁no▁2｜>", "<｜hy_end▁of▁sentence｜>"]
AI_MARKER = "[AI-generated by ASRSub]"
AI_MARKER_CUE = os.environ.get("AI_MARKER_CUE", "1") != "0"
AI_MARKER_CUE_MS = int(os.environ.get("AI_MARKER_CUE_MS", "1500"))
ASR_BACKEND = os.environ.get("ASR_BACKEND", "whisper")
DEFAULT_SDH_PLACEHOLDERS = ["（歌詞）"]  # (Lirik lagu) and friends; config-driven via sdh_placeholders

_stop_requested = False
_paused = False
_run_once_requested = False
_last_pass_stats = None
_started_at = datetime.now(timezone.utc)
_consecutive_failures = 0
_HELP_COOLDOWN = {}
_GLOBAL_HELP_LAST = 0.0


def _handle_sigterm(signum, frame):
    global _stop_requested
    _stop_requested = True
    WAKE_EVENT.set()
    log("SIGTERM received, finishing current pass then exiting")


def load_config():
    cfg = {}
    with open(ENV_FILE, "r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            cfg[k.strip()] = v.strip()
    if os.path.exists(OVERRIDE_FILE):
        try:
            with open(OVERRIDE_FILE, "r", encoding="utf-8") as fh:
                ov = json.loads(fh.read())
            if isinstance(ov, dict):
                for k, v in ov.items():
                    cfg[str(k)] = str(v)
        except Exception as exc:
            log(f"WARNING: failed to load {OVERRIDE_FILE}: {exc}")
    cfg["MAX_EPS_PER_RUN"] = int(
        os.environ.get("MAX_EPS_PER_RUN", cfg.get("MAX_EPS_PER_RUN", "8"))
    )
    tl = cfg.get("TARGET_LANGS", "id,en")
    if isinstance(tl, str) and tl.strip().startswith("["):
        try:
            import ast

            tl = ast.literal_eval(tl)
        except Exception:
            tl = "id,en"
    if isinstance(tl, list):
        tl = ",".join(x for x in tl if isinstance(x, str))
    cfg["TARGET_LANGS"] = [
        x.strip() for x in str(tl).split(",") if x.strip()
    ]
    cfg["STATE_FILE"] = STATE_FILE
    cfg["JELLYFIN_URL"] = cfg.get("JELLYFIN_URL") or JELLYFIN_URL
    cfg["JELLYFIN_MEDIA_ROOT"] = cfg.get("JELLYFIN_MEDIA_ROOT") or JELLYFIN_MEDIA_ROOT
    sdh = cfg.get("sdh_placeholders")
    if isinstance(sdh, str):
        try:
            sdh = json.loads(sdh)
        except Exception:
            try:
                import ast

                sdh = ast.literal_eval(sdh)
            except Exception:
                sdh = None
    cfg["SDH_PLACEHOLDERS"] = list(sdh) if isinstance(sdh, list) else list(DEFAULT_SDH_PLACEHOLDERS)
    return cfg


def log(msg):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    with _LOG_LOCK:
        _LOG_RING.append(f"{ts} {msg}")
        print(f"{ts} {msg}", flush=True)


# ---------- state ----------


def load_state():
    entries = []
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        entries.append(json.loads(line))
                    except Exception:
                        pass
    if len(entries) > STATE_COMPACT_LINES:
        entries = _compact_state(entries)
    return entries


STATE_COMPACT_LINES = 2000
STATE_COMPACT_DAYS = 14
STATE_GC_AGE = 24 * 3600  # fileless rows older than this are pruned
STATE_GC_CAP = 500  # max unique episode ids queried per GC sweep
STATE_GC_CHUNK = 200  # per-call cap when a sweep must be chunked

# Session-memoized Sonarr knowledge for orphan GC. Never re-queried within one
# daemon lifetime. Value = {"monitored": bool, "hasFile": bool} for episodes
# known to Sonarr, None for ghosts (deleted from Sonarr). state.jsonl is only
# ever written by this daemon (append_state / _compact_state / gc_state), so
# no cross-process race on these writes.
_GC_KNOWN = {}


def fetch_sonarr_episode_map(cfg):
    """One series-list call + one episode-list call per series (~15 series ->
    ~16 calls instead of one call per episode). Returns
    {episode_id: {"monitored": bool, "hasFile": bool}} for every episode
    Sonarr knows; raises on HTTP failure, returns None when the response
    shape is unusable (never a partial/empty map that would look like every
    episode is a ghost)."""
    base = cfg["SONARR_URL"].rstrip("/")
    headers = {"X-Api-Key": cfg["SONARR_API_KEY"]}
    r = requests.get(base + "/series", headers=headers, timeout=60)
    r.raise_for_status()
    series = r.json()
    if not isinstance(series, list):
        return None
    info = {}
    for s in series:
        if not isinstance(s, dict):
            continue
        sid = s.get("id")
        if sid is None:
            continue
        r2 = requests.get(
            base + "/episode", params={"seriesId": sid}, headers=headers, timeout=60
        )
        r2.raise_for_status()
        eps = r2.json()
        if not isinstance(eps, list):
            return None
        for e in eps:
            if not isinstance(e, dict):
                continue
            eid = e.get("id")
            if isinstance(eid, int):
                info[eid] = {
                    "monitored": bool(e.get("monitored")),
                    "hasFile": bool(e.get("hasFile")),
                }
    return info


def mark_ghost(eid):
    """Record that Sonarr returned 404 for this episode id (get_episode in
    run_pass/consume_actions) so the next GC sweep prunes its state rows."""
    if isinstance(eid, int):
        _GC_KNOWN[eid] = None


def gc_state(cfg, entries, cap=STATE_GC_CAP, age=STATE_GC_AGE):
    """Orphan GC over state entries.

    Drops rows whose episode no longer exists in Sonarr (ghost) and rows for
    episodes with no video file when the row is older than 24h (age guard;
    unparseable ts is KEPT, same convention as _compact_state). Never drops
    rows for monitored episodes that have video files (retryable), and leaves
    unmonitored-but-fileless rows alone when fresh. Only checks episode ids
    not yet queried this daemon lifetime (_GC_KNOWN). Rewrites state.jsonl
    atomically (tmp + os.replace) when rows were dropped.

    Returns (kept_entries, {"dropped", "ghost", "fileless"})."""
    if not entries:
        return entries, {"dropped": 0, "ghost": 0, "fileless": 0}
    unique_ids = sorted(
        {
            e.get("sonarrEpisodeId")
            for e in entries
            if isinstance(e.get("sonarrEpisodeId"), int)
        }
    )
    if not unique_ids:
        return entries, {"dropped": 0, "ghost": 0, "fileless": 0}
    todo = [i for i in unique_ids if i not in _GC_KNOWN][:cap]
    if todo:
        try:
            info = fetch_sonarr_episode_map(cfg)
        except Exception as exc:
            log(f"GC: Sonarr scan failed ({exc}); skipping sweep, retry next pass")
            return entries, {"dropped": 0, "ghost": 0, "fileless": 0}
        if not info:
            log("GC: Sonarr returned no episode map; skipping sweep")
            return entries, {"dropped": 0, "ghost": 0, "fileless": 0}
        for i in todo:
            _GC_KNOWN[i] = info.get(i)  # absent => ghost
    cutoff = time.time() - age
    kept, ghost, fileless = [], 0, 0
    for e in entries:
        eid = e.get("sonarrEpisodeId")
        if not isinstance(eid, int) or eid not in _GC_KNOWN:
            kept.append(e)  # never checked yet: keep until a sweep resolves it
            continue
        st = _GC_KNOWN[eid]
        if st is None:
            ghost += 1
            continue
        if not st.get("hasFile"):
            ts = e.get("ts", "")
            try:
                row_age = datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
            except Exception:
                row_age = cutoff + 1  # unknown age: keep (cannot prove old)
            if row_age < cutoff:
                fileless += 1
                continue
        kept.append(e)
    dropped = ghost + fileless
    if dropped:
        rewrite_jsonl(STATE_FILE, kept)
        log(
            f"state GC: dropped {dropped} rows ({ghost} ghost, {fileless} fileless) "
            f"from {len(entries)} entries, {len(kept)} kept"
        )
    return kept, {"dropped": dropped, "ghost": ghost, "fileless": fileless}


def _compact_state(entries):
    """Compact state.jsonl (>2000 entries): keep only the LATEST entry per
    (sonarrEpisodeId, language) and drop entries older than 14 days; write
    atomically (tmp + os.replace). Never changes the entry schema."""
    cutoff = time.time() - STATE_COMPACT_DAYS * 24 * 3600
    last_idx = {}
    for i, e in enumerate(entries):
        key = (e.get("sonarrEpisodeId"), e.get("language"))
        last_idx[key] = i
    kept = []
    for i, e in enumerate(entries):
        if last_idx.get((e.get("sonarrEpisodeId"), e.get("language"))) != i:
            continue  # newer entry exists for this (episode, language)
        ts = e.get("ts", "")
        try:
            age = datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
        except Exception:
            age = cutoff + 1  # unknown age: keep (cannot prove it is old)
        if age < cutoff:
            continue
        kept.append(e)
    if len(kept) < len(entries):
        rewrite_jsonl(STATE_FILE, kept)
        log(
            f"state compacted: {len(entries)} -> {len(kept)} entries "
            f"(latest per episode+language, <{STATE_COMPACT_DAYS}d kept)"
        )
    return kept


def append_state(entry):
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    entry["ts"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    with open(STATE_FILE, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry, ensure_ascii=False) + "\n")


def load_records_jsonl(path):
    """Parse a jsonl of dicts, tolerating empty/garbage lines."""
    records = []
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    records.append(json.loads(line))
                except Exception:
                    continue
    return records


def consume_records_jsonl(path):
    """Read a jsonl and remove the consumed records in place.

    Holds an exclusive flock (fcntl) on the single "r+" handle around the
    read/truncate/write, so a producer appending under the same flock
    protocol is serialized: any bytes appended after our last readline are
    rewritten as the new file tail — the consumed prefix is gone, concurrent
    records survive, and no record is processed twice or lost."""
    records = []
    if os.path.exists(path):
        with open(path, "r+", encoding="utf-8") as fh:
            fcntl.flock(fh, fcntl.LOCK_EX)
            try:
                while True:
                    line = fh.readline()
                    if not line:
                        break
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        records.append(json.loads(line))
                    except Exception:
                        continue
                tail = fh.read()
                fh.seek(0)
                fh.truncate(0)
                fh.write(tail)
                fh.flush()
            finally:
                fcntl.flock(fh, fcntl.LOCK_UN)
    return records


def rewrite_jsonl(path, records):
    """Atomic rewrite of a jsonl file (temp file + os.replace)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        for rec in records:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
    os.replace(tmp, path)


def parse_exclusions():
    """Excluded episode ids from exclusions.jsonl ({'episode_id': N, ...})."""
    ids = set()
    for rec in load_records_jsonl(EXCLUSIONS_FILE):
        eid = rec.get("episode_id")
        if isinstance(eid, int):
            ids.add(eid)
    return ids


# ---------- remote APIs ----------


def get_wanted(cfg):
    r = requests.get(
        cfg["BAZARR_URL"].rstrip("/") + "/episodes/wanted",
        params={"start": 0, "length": 500},
        headers={"X-API-KEY": cfg["BAZARR_API_KEY"]},
        timeout=60,
    )
    r.raise_for_status()
    return r.json()


def get_episode(cfg, ep_id):
    r = requests.get(
        cfg["SONARR_URL"].rstrip("/") + f"/episode/{ep_id}",
        headers={"X-Api-Key": cfg["SONARR_API_KEY"]},
        timeout=60,
    )
    if r.status_code == 404:
        # ghost: episode deleted from Sonarr; GC prunes its state rows next sweep
        mark_ghost(ep_id)
    r.raise_for_status()
    return r.json()


def map_path(container_path):
    if container_path.startswith("/data/"):
        return "/mnt/nas/share/media/" + container_path[len("/data/") :]
    return container_path


def probe_audio(path):
    p = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "stream=index,codec_name,codec_type:stream_tags=language",
            "-of",
            "json",
            path,
        ],
        capture_output=True,
        text=True,
        timeout=300,
    )
    if p.returncode != 0:
        raise RuntimeError(f"ffprobe failed: {p.stderr.strip()}")
    data = json.loads(p.stdout)
    return [s for s in data.get("streams", []) if s.get("codec_type") == "audio"]


def choose_source(streams, target_lang):
    if not streams:
        return None
    lang_of = lambda s: s.get("tags", {}).get("language")
    if target_lang == "en":
        eng = next((s for s in streams if lang_of(s) == "eng"), None)
        if eng is not None:
            return {
                "stream_index": eng["index"],
                "asr_lang": "en",
                "needs_translate": False,
                "src_lang": "eng",
            }
    jpn = next((s for s in streams if lang_of(s) == "jpn"), None)
    s = jpn if jpn is not None else streams[0]
    tag = lang_of(s) or ""
    asr_lang = {"jpn": "ja", "eng": "en"}.get(tag, "en")
    return {
        "stream_index": s["index"],
        "asr_lang": asr_lang,
        "needs_translate": asr_lang != target_lang,
        "src_lang": tag or "?",
    }


def extract_wav(path, stream_index, out_path):
    p = subprocess.run(
        [
            "ffmpeg",
            "-nostdin",
            "-v",
            "error",
            "-y",
            "-i",
            path,
            "-map",
            f"0:{stream_index}",
            "-ac",
            "1",
            "-ar",
            "16000",
            "-c:a",
            "pcm_s16le",
            out_path,
        ],
        capture_output=True,
        text=True,
        timeout=900,
    )
    if p.returncode != 0:
        raise RuntimeError(f"ffmpeg extract failed: {p.stderr.strip()}")


def _media_fingerprint(path):
    st = os.stat(path)
    return {"size": st.st_size, "mtime_ns": st.st_mtime_ns}


def _asr_cache_dims():
    """ASR config dimensions that change segmentation; cache entries written
    under other dims are treated as a miss so stale cues are never served
    (e.g. sensevoice production vs faster-whisper refine sharing one key)."""
    dims = {"backend": ASR_BACKEND}
    if ASR_BACKEND == "sensevoice":
        for k in (
            "SV_MAX_SEG_MS",
            "SV_MAX_END_SILENCE_MS",
            "SV_SPEECH_PAD_MS",
            "SV_MIN_SPEECH_MS",
        ):
            dims[k] = os.environ.get(k, "")
    else:
        for k in (
            "WHISPER_MODEL",
            "WHISPER_BEAM",
            "VAD_THRESHOLD",
            "VAD_MIN_SILENCE_MS",
            "VAD_MAX_SPEECH_S",
            "VAD_MIN_SILENCE_AT_MAX",
            "VAD_SPEECH_PAD_MS",
            "SPLIT_MIN_SILENCE_MS",
            "MAX_CUE_MS",
            "HARD_GAP_MS",
        ):
            dims[k] = os.environ.get(k, "")
    return dims


def asr_cache_get(ep_id, asr_lang, media_path):
    key = f"{ep_id}_{asr_lang}"
    cues_path = os.path.join(ASR_CACHE_DIR, key + ".cues.json")
    meta_path = os.path.join(ASR_CACHE_DIR, key + ".json")
    try:
        with open(meta_path) as fh:
            meta = json.load(fh)
        if meta.get("fingerprint") == _media_fingerprint(media_path) and meta.get(
            "asr_dims"
        ) == _asr_cache_dims():
            with open(cues_path) as fh:
                cues = json.load(fh)
            if cues and isinstance(cues, list):
                return cues
    except Exception:
        pass
    return None


def asr_cache_put(ep_id, asr_lang, media_path, cues):
    os.makedirs(ASR_CACHE_DIR, exist_ok=True)
    key = f"{ep_id}_{asr_lang}"
    with open(os.path.join(ASR_CACHE_DIR, key + ".cues.json"), "w") as fh:
        json.dump(cues, fh, ensure_ascii=False)
    with open(os.path.join(ASR_CACHE_DIR, key + ".json"), "w") as fh:
        json.dump(
            {"fingerprint": _media_fingerprint(media_path), "asr_dims": _asr_cache_dims()},
            fh,
        )


def asr_cues(cfg, wav_path, lang):
    """ASR dispatch. Default: faster-whisper + VadOptions (<=8s cues).
    ASR_BACKEND=sensevoice: SenseVoice + fsmn-vad 5s cap + min-1s post-pass
    (validated recipe 2026-08-10); SenseVoice language codes ja/zh/en/ko/yue."""
    if ASR_BACKEND == "sensevoice":
        from pipeline import sensevoice as pipeline_sensevoice

        return pipeline_sensevoice.transcribe_cues(wav_path, language=lang)
    return pipeline_asr.transcribe_cues(wav_path, language=lang)


# ---------- SRT ----------


def parse_srt(text):
    cues = []
    for block in re.split(r"\n\s*\n", text.strip()):
        lines = [l.strip() for l in block.splitlines() if l.strip()]
        if not lines:
            continue
        ts_idx = next((i for i, l in enumerate(lines) if "-->" in l), None)
        if ts_idx is None:
            continue
        m = re.match(
            r"(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})",
            lines[ts_idx],
        )
        if not m:
            continue
        body = " ".join(lines[ts_idx + 1 :]).strip()
        if not body:
            continue
        cues.append({"start": m.group(1), "end": m.group(2), "text": body})
    return cues


def _fmt_ms(ms):
    ms = int(round(ms))
    h, rem = divmod(ms, 3600000)
    m, rem = divmod(rem, 60000)
    s, msr = divmod(rem, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{msr:03d}"


def _fmt_ts(v):
    if isinstance(v, (int, float)):
        return _fmt_ms(v)
    return v


def write_srt(cues, texts, out_path, header=None):
    """Write SRT. header (AI marker) becomes a REAL first cue at 00:00:00,000
    -> 00:00:01,500 (config AI_MARKER_CUE, default on) — bare text lines are
    dropped by players until a timestamped cue is seen. If the first dialogue
    cue starts before 2s, the marker cue ends just before it."""
    with open(out_path, "w", encoding="utf-8") as fh:
        idx = 1
        if header and AI_MARKER_CUE:
            first_start = None
            for cue in cues:
                if cue.get("text", "").strip():
                    first_start = cue.get("start")
                    break
            marker_end = AI_MARKER_CUE_MS
            if first_start is not None and first_start < 2000:
                marker_end = max(0, first_start - 1)
            fh.write(
                f"{idx}\n00:00:00,000 --> {_fmt_ms(marker_end)}\n{header}\n\n"
            )
            idx = 2
        elif header:
            fh.write(header + "\n\n")
        for cue, text in zip(cues, texts):
            fh.write(
                f"{idx}\n{_fmt_ts(cue['start'])} --> {_fmt_ts(cue['end'])}\n{text}\n\n"
            )
            idx += 1


# ---------- translation (Zen Go, OpenAI-compatible) ----------


def extract_json_array(raw):
    if not raw:
        return None
    s = raw.strip()
    i, j = s.find("["), s.rfind("]")
    if i < 0 or j <= i:
        return None
    for cand in (s[i : j + 1], raw[i : j + 1]):
        try:
            arr = json.loads(cand)
            if isinstance(arr, list):
                return [str(x) for x in arr]
        except Exception:
            continue
    return None


def post_chat(cfg, messages, model, key, local=False):
    url = (cfg.get("TRANSLATE_BASE") or TRANSLATE_BASE).rstrip(
        "/"
    ) + "/chat/completions"
    headers = {"Authorization": f"Bearer {key}", "Content-Type": "application/json"}
    if local:
        payload = {
            "model": model,
            "messages": messages,
            "temperature": 0.1,
            "top_k": 20,
            "top_p": 0.6,
            "repeat_penalty": 1.0,
            "max_tokens": 8192,
            "stop": HY_STOP_TOKENS,
        }
    else:
        payload = {
            "model": model,
            "messages": messages,
            "temperature": 0.3,
            "thinking": {"type": "enabled", "effort": "max"},
        }
    for attempt in range(3):
        try:
            r = requests.post(url, headers=headers, json=payload, timeout=TIMEOUT)
        except requests.RequestException as exc:
            log(f"    [translate] network error (attempt {attempt + 1}): {exc}")
            if attempt < 2:
                time.sleep(5 * (attempt + 1))
            continue
        if r.status_code == 200:
            try:
                return r.json()["choices"][0]["message"]["content"]
            except Exception:
                return None
        if r.status_code == 404:
            return None  # signal model fallback
        if (
            local
            and r.status_code == 400
            and "exceeds the available context size" in r.text
        ):
            # deterministic context overflow: retrying the same size always fails.
            # Signal the caller to split the chunk instead of deferring.
            log(
                f"    [translate] HTTP 400 context overflow (attempt {attempt + 1}): {r.text[:200]} - splitting chunk"
            )
            return CTX_OVERFLOW
        # 5xx/429: server overload or rate limit - do not hammer; defer to next pass
        log(
            f"    [translate] HTTP {r.status_code} (attempt {attempt + 1}): {r.text[:200]} - deferring to next pass"
        )
        return None
    return None


def get_prior_context(cfg, series_id, episode_id):
    try:
        r = requests.get(
            cfg["SONARR_URL"].rstrip("/") + "/episode",
            params={"seriesId": series_id},
            headers={"X-Api-Key": cfg["SONARR_API_KEY"]},
            timeout=60,
        )
        r.raise_for_status()
        current = get_episode(cfg, episode_id)
        season = current.get("seasonNumber")
        episode_num = current.get("episodeNumber")
        if not isinstance(season, int) or not isinstance(episode_num, int):
            return []
        prev_nums = {episode_num - 1, episode_num - 2}
        prev_eps = [
            e
            for e in r.json()
            if e.get("seasonNumber") == season and e.get("episodeNumber") in prev_nums
        ]
        lines = []
        seen = set()
        for prev in sorted(prev_eps, key=lambda e: -e["episodeNumber"]):
            if len(lines) >= 20:
                break
            try:
                sr = requests.get(
                    cfg["BAZARR_URL"].rstrip("/") + "/episodes",
                    params={"episodeid[]": prev["id"]},
                    headers={"X-API-KEY": cfg["BAZARR_API_KEY"]},
                    timeout=60,
                )
                if sr.status_code != 200:
                    continue
                data = sr.json()
            except Exception:
                continue
            if not isinstance(data, dict):
                continue
            items = data.get("data") or []
            if not items:
                continue
            subs = items[0].get("subtitles") or []
            subs.sort(key=lambda s: 0 if (s.get("code2") or "") == "id" else 1)
            chosen = None
            for s in subs:
                p = s.get("path")
                if not p:
                    continue
                local = map_path(p)
                if os.path.isfile(local):
                    chosen = local
                    break
            if not chosen:
                continue
            try:
                with open(chosen, "r", encoding="utf-8", errors="replace") as fh:
                    srt_text = fh.read()
                for cue in parse_srt(srt_text):
                    t = cue["text"]
                    if t and t not in seen:
                        seen.add(t)
                        lines.append(t)
                        if len(lines) >= 40:
                            break
            except Exception:
                continue
        return lines[:20]
    except Exception:
        return []


def is_local_translate(cfg):
    base = cfg.get("TRANSLATE_BASE") or TRANSLATE_BASE
    return "127.0.0.1" in base or "localhost" in base


def _parse_numbered_response(raw):
    if not raw:
        return None
    parsed = {}
    for line in raw.splitlines():
        m = re.match(r"^(\d+)[.．…]?\s*(.+)$", line.strip())
        if m:
            parsed[int(m.group(1))] = m.group(2).strip()
    return parsed


def sanitize_lines(lines, max_repeat=10):
    """Collapse runs of >max_repeat identical chars to max_repeat + ellipsis
    (anime scream lines otherwise trigger repetition collapse in small models)."""
    out = []
    for s in lines:
        if not s:
            out.append(s)
            continue
        parts = []
        i = 0
        while i < len(s):
            j = i
            while j < len(s) and s[j] == s[i]:
                j += 1
            run = j - i
            if run > max_repeat:
                parts.append(s[i] * max_repeat + "…")
            else:
                parts.append(s[i:j])
            i = j
        out.append("".join(parts))
    return out


def guard_foreign_lines(lines, sdh_placeholders=None):
    """Replace foreign-script lines (Chinese w/o kana, mostly-latin English) with an
    SDH placeholder (default （歌詞）) so the model does not echo the whole chunk.
    Returns (guarded_lines, [(original_index, original_text), ...]) for swap-back."""
    sdh = list(sdh_placeholders) if sdh_placeholders else list(DEFAULT_SDH_PLACEHOLDERS)
    out, foreign = [], []
    for i, l in enumerate(lines):
        latin_chars = LATIN_RE.findall(l)
        latin_ratio = len(latin_chars) / max(len(l), 1)
        if (HANZI_RE.search(l) and not KANA_RE.search(l)) or (
            latin_ratio > 0.5 and not KANA_RE.search(l)
        ):
            foreign.append((i, l))
            out.append(sdh[i % len(sdh)])
        else:
            out.append(l)
    return out, foreign


def _local_chunk(cfg, chunk, lang_name, key, refs=None):
    """One local-model chat call for a numbered chunk. Returns parsed dict
    num->text (via _parse_numbered_response) or None on network failure.
    refs: HY-MT1.5 official terminology-intervention line (glossary) or None."""
    n = len(chunk)
    system = (
        f"Translate each line into {lang_name}. Reply as numbered list, "
        f"e.g. 1. ... 2. ... 3. ..., exactly {n} lines, no extra text."
    )
    if refs:
        system += "\n\n参考下面的翻译：\n" + refs
    prompt = system + "\n\n" + "\n".join(f"{i}. {l}" for i, l in enumerate(chunk, 1))
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": prompt},
    ]
    raw = post_chat(cfg, messages, cfg.get("TRANSLATE_MODEL") or TRANSLATE_MODEL, key, local=True)
    if raw is None:
        return None
    return _parse_numbered_response(raw)


def _attempt_chunk(cfg, chunk, lang_name, key, echo_probe=11, refs=None):
    """Up to 3 attempts per chunk; corrective retry on echo. Returns clean
    parsed dict or None (all attempts empty/echo/network-fail)."""
    n = len(chunk)
    for _ in range(3):
        parsed = _local_chunk(cfg, chunk, lang_name, key, refs=refs)
        if not parsed:
            continue
        echo = False
        for k in range(1, min(echo_probe, n) + 1):
            t = parsed.get(k)
            if t and re.search(r"[\u3040-\u30ff\u3400-\u9fff]", t):
                echo = True
                break
        if not echo:
            return parsed
    return None


def _complete_tail(cfg, tail_lines, m, lang_name, key, refs=None):
    """Complete a chunk's missing tail: translate source lines m..n-1
    (numbered m+1..n in the prompt), remap keys to absolute m+i. Returns
    merged dict for the full chunk (keys 1..n) or None after 3 attempts."""
    n = m + len(tail_lines)
    for _ in range(3):
        system = (
            f"Translate each line into {lang_name}. Reply as numbered list, "
            f"e.g. 1. ... 2. ... 3. ..., exactly {n - m} lines, no extra text."
        )
        if refs:
            system += "\n\n参考下面的翻译：\n" + refs
        prompt = (
            system
            + "\n\n"
            + "\n".join(f"{i + 1}. {l}" for i, l in enumerate(tail_lines))
        )
        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ]
        raw = post_chat(cfg, messages, cfg.get("TRANSLATE_MODEL") or TRANSLATE_MODEL, key, local=True)
        if raw is None:
            continue
        parsed = _parse_numbered_response(raw)
        if not parsed:
            continue
        echo = False
        for rel in range(1, min(5, n - m) + 1):
            t = parsed.get(rel)
            if t and re.search(r"[\u3040-\u30ff\u3400-\u9fff]", t):
                echo = True
                break
        if echo:
            continue
        return {m + i: text for i, text in parsed.items()}
    return None


def _translate_merge_aware(cfg, lines, lang_name, key, refs=None):
    """Translate, tolerating HY-MT merging consecutive short lines. Returns
    list of (cue_start_idx, cue_end_idx_exclusive, text)."""
    groups = []
    cs = TRANSLATE_CHUNK
    for start in range(0, len(lines), cs):
        chunk = lines[start : start + cs]
        n = len(chunk)
        parsed = _attempt_chunk(cfg, chunk, lang_name, key, refs=refs)
        if parsed is None:
            for j in range(n):
                gi = start + j
                p = _attempt_chunk(cfg, [chunk[j]], lang_name, key, echo_probe=1, refs=refs)
                text = re.sub(r"^>\s*", "", (p or {}).get(1, ""))
                groups.append((gi, gi + 1, text))
            continue
        entries = sorted(parsed.items())
        m = len(entries)
        if m == n:
            for k, t in entries:
                if k < 1 or k > n:
                    continue
                groups.append((start + k - 1, start + k, re.sub(r"^>\s*", "", t)))
            continue
        entries_dict = dict(entries)
        tail_lines = chunk[m:n]
        merged = None
        if tail_lines:
            completion = _complete_tail(cfg, tail_lines, m, lang_name, key, refs=refs)
            if completion:
                merged = {**entries_dict, **completion}
        if merged:
            for k, t in sorted(merged.items()):
                if k > n:
                    continue
                groups.append((start + k - 1, start + k, re.sub(r"^>\s*", "", t)))
        else:
            for k, t in entries:
                if k > n:
                    continue
                gi = start + k - 1
                groups.append((gi, gi + 1, re.sub(r"^>\s*", "", t)))
            for k in range(m + 1, n + 1):
                gi = start + k - 1
                p = _attempt_chunk(cfg, [chunk[k - 1]], lang_name, key, echo_probe=1, refs=refs)
                text = re.sub(r"^>\s*", "", (p or {}).get(1, ""))
                groups.append((gi, gi + 1, text))
    return groups


def chat_translate_batch(cfg, lines, target_lang, key, context_lines=None, series_title=None):
    lines = sanitize_lines(lines)
    if is_local_translate(cfg):
        # local 7B path: merge-aware numbered protocol with HY-MT1.5 official
        # terminology intervention (glossary). Foreign lines become SDH
        # placeholders (kept in output, not swapped back).
        sdh = cfg.get("SDH_PLACEHOLDERS") or DEFAULT_SDH_PLACEHOLDERS
        lines, _foreign = guard_foreign_lines(lines, sdh)
        term = pipeline_glossary.terminology_block(series_title)
        if term:
            log(f"    [translate] glossary terminology for series: {len(term)} chars")
        lang_name = LANG_NAMES.get(target_lang, target_lang)
        return _translate_merge_aware(cfg, lines, lang_name, key, refs=term)
    models = [cfg.get("TRANSLATE_MODEL") or TRANSLATE_MODEL] + [
        m for m in MODEL_FALLBACKS if m != cfg.get("TRANSLATE_MODEL")
    ]
    system = TRANSLATE_PROMPT.format(target_language=target_lang)
    if context_lines:
        system += (
            "\n\nUse these previously translated lines from earlier episodes for "
            "consistent names, terms, and style:\n"
            + "\n".join(f"REF: {l}" for l in context_lines)
        )
    user = json.dumps(
        {"target_language": target_lang, "lines": lines}, ensure_ascii=False
    )
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]
    for _ in range(2):  # one corrective retry on parse failure
        raw = None
        for model in models:
            content = post_chat(cfg, messages, model, key)
            if content is None:
                continue  # 404 -> next model, or network dead -> try next model too
            raw = content
            break
        if raw is None:
            log("    [translate] all models/attempts failed (network or 404)")
            return None
        parsed = extract_json_array(raw)
        if parsed is not None and len(parsed) == len(lines):
            return parsed
        messages.append({"role": "assistant", "content": raw})
        messages.append(
            {
                "role": "user",
                "content": (
                    f"Your previous output was not a JSON array with exactly {len(lines)} "
                    'strings. Output ONLY the JSON array, e.g. ["...", "..."], same count '
                    "and order as the input."
                ),
            }
        )
    log("    [translate] unparseable / count mismatch after retry")
    return None


def translate_texts(
    cfg,
    cues,
    target_lang,
    key,
    series_id=None,
    episode_id=None,
    prior_cache=None,
    series_title=None,
):
    lines = [c["text"] for c in cues]
    if is_local_translate(cfg):
        context_lines = []
    elif series_id and episode_id and prior_cache is not None:
        if series_id not in prior_cache:
            prior_cache[series_id] = get_prior_context(cfg, series_id, episode_id)
        context_lines = prior_cache[series_id]
    else:
        context_lines = (
            get_prior_context(cfg, series_id, episode_id)
            if series_id and episode_id
            else []
        )
    out = chat_translate_batch(
        cfg, lines, target_lang, key, context_lines, series_title=series_title
    )
    if out is None:
        return None
    if is_local_translate(cfg):
        # merge-aware groups (start_idx, end_idx_excl, text); caller assembles cues
        return out
    if len(out) != len(lines):
        return None
    return [(i, i + 1, t) for i, t in enumerate(out)]


# ---------- upload ----------


def jellyfin_refresh(cfg, media_path, title=None):
    """Fire-and-forget Jellyfin library refresh for a subtitle event.

    Finds the episode item by SearchTerm (=episode title, fallback filename),
    matches Path against the media file (mapped NAS path), then POSTs
    /Items/{id}/Refresh (204). Runs in a daemon thread, ~5s timeouts; failures
    are logged but never fail the episode. No-op without JELLYFIN_API_KEY.
    """
    key = cfg.get("JELLYFIN_API_KEY", "")
    if not key or not media_path:
        return

    def _run():
        try:
            base = (cfg.get("JELLYFIN_URL") or JELLYFIN_URL).rstrip("/")
            root = cfg.get("JELLYFIN_MEDIA_ROOT") or JELLYFIN_MEDIA_ROOT
            jelly_path = (
                root + media_path[len("/mnt/nas/share/media"):]
                if media_path.startswith("/mnt/nas/share/media")
                else media_path
            )
            filename = os.path.basename(media_path)
            headers = {"X-Emby-Token": key}
            r = requests.get(
                base + "/Items",
                params={
                    "Recursive": "true",
                    "IncludeItemTypes": "Episode",
                    "SearchTerm": title or filename,
                    "Fields": "Path,MediaStreams",
                },
                headers=headers,
                timeout=5,
            )
            r.raise_for_status()
            item = None
            for it in r.json().get("Items", []):
                p = it.get("Path") or ""
                if p == jelly_path or p.endswith("/" + filename):
                    item = it
                    break
            if item is None:
                log(f"jellyfin: episode item not found for {filename}")
                return
            body = {
                "MetadataRefreshMode": "FullRefresh",
                "ImageRefreshMode": "None",
                "ReplaceAllMetadata": False,
                "ReplaceAllImages": False,
            }
            rr = requests.post(
                base + f"/Items/{item['Id']}/Refresh",
                json=body,
                headers=headers,
                timeout=5,
            )
            log(f"jellyfin: refresh {filename} HTTP {rr.status_code}")
        except Exception as exc:
            log(f"jellyfin: refresh failed for {media_path}: {exc}")

    threading.Thread(target=_run, daemon=True).start()


def _delete_episode_subtitles(cfg, ep_id, langs=None):
    """Remove {video stem}.{lang}.srt files (NAS path) plus TMP_DIR copies
    the pipeline wrote for the episode. langs=None deletes all TARGET_LANGS;
    otherwise only the listed languages. Never raises."""
    deleted = []
    langs = langs or list(cfg.get("TARGET_LANGS", []))
    try:
        info = get_episode(cfg, ep_id)
        ef = info.get("episodeFile") or {}
        p = map_path(ef.get("path", "")) if ef.get("path") else ""
        if p and os.path.isfile(p):
            stem = os.path.splitext(p)[0]
            for lang in langs:
                cand = f"{stem}.{lang}.srt"
                if os.path.isfile(cand):
                    try:
                        os.remove(cand)
                        deleted.append(cand)
                    except OSError:
                        pass
    except Exception as exc:
        log(f"action: delete: locating episode {ep_id} failed: {exc}")
    for lang in langs:
        cand = os.path.join(cfg.get("TMP_DIR", "/tmp"), f"{ep_id}_{lang}.srt")
        if os.path.isfile(cand):
            try:
                os.remove(cand)
                deleted.append(cand)
            except OSError:
                pass
    return deleted


def consume_actions(cfg):
    """Process pending actions.jsonl records once per pass; consumed records
    removed in place (tail-preserving: records appended mid-pass survive).

    schema (dashboard control_api_v2): {"ts", "type": "retry"|"skip"|"delete",
    "episode_id": int, "language": null|<code>, "source", "note"} —
    "action" is accepted as an alias for "type", and "language" limits retry
    to specific languages (null = the whole episode).

    - skip:   episode excluded from this pass's candidates
    - retry:  state entries cleared AND the episode's subtitle files removed
              (same _delete_episode_subtitles as delete): Bazarr wanted only
              lists episodes with MISSING subtitles, so clearing state alone
              would never reprocess an episode whose .srt is on disk
              (dashboard Retry would be dead); with the file gone the episode
              re-enters Bazarr wanted and is regenerated. "language" limits
              the state clearing AND the subtitle-file deletion to matching
              languages (null = whole episode).
    - delete: NAS + TMP SRT files removed, done state cleared -> regenerates,
              then Jellyfin refresh so the removed subtitle is dropped.
              "language" scopes the file deletion and state clearing to
              matching languages (null = whole episode), like retry.
    Returns the set of episode ids to exclude this pass (skips)."""
    records = consume_records_jsonl(ACTIONS_FILE)
    if not records:
        return set()
    skip_ids, retry_ids, delete_ids = set(), set(), set()
    retry_langs = {}
    delete_langs = {}
    for rec in records:
        eid = rec.get("episode_id")
        if not isinstance(eid, int):
            continue
        action = rec.get("type") or rec.get("action") or ""
        if action == "skip":
            skip_ids.add(eid)
        elif action in ("retry", "delete"):
            ids = retry_ids if action == "retry" else delete_ids
            langs = retry_langs if action == "retry" else delete_langs
            ids.add(eid)
            lang = rec.get("language")
            entry = langs.setdefault(eid, set())
            if isinstance(lang, str) and lang:
                entry.add(lang)
            else:
                entry.add(None)  # null language = whole episode
    if retry_ids or delete_ids:
        states = load_state()
        kept = []
        changed = False
        for e in states:
            eid = e.get("sonarrEpisodeId")
            lang = e.get("language")
            drop = False
            if isinstance(eid, int) and eid in retry_ids:
                langs = retry_langs.get(eid)
                drop = not langs or (None in langs) or (lang in langs)
            elif isinstance(eid, int) and eid in delete_ids:
                langs = delete_langs.get(eid)
                drop = not langs or (None in langs) or (lang in langs)
            if drop:
                changed = True
            else:
                kept.append(e)
        if changed:
            rewrite_jsonl(STATE_FILE, kept)
    for eid in sorted(delete_ids):
        langs = delete_langs.get(eid)
        all_langs = not langs or None in langs
        deleted = _delete_episode_subtitles(
            cfg, eid, langs=None if all_langs else sorted(langs)
        )
        log(f"action: delete episode {eid} (removed {len(deleted)} SRTs, state cleared)")
        media_path, title = "", None
        try:
            info = get_episode(cfg, eid)
            ef = info.get("episodeFile") or {}
            media_path = map_path(ef.get("path", "")) if ef.get("path") else ""
            title = info.get("title") or info.get("Name")
        except Exception:
            pass
        if media_path:
            jellyfin_refresh(cfg, media_path, title)
    for eid in sorted(retry_ids):
        langs = retry_langs.get(eid)
        all_langs = not langs or None in langs
        deleted = _delete_episode_subtitles(
            cfg, eid, langs=None if all_langs else sorted(langs)
        )
        log(f"action: retry episode {eid} (state cleared, {len(deleted)} SRTs removed)")
    for eid in sorted(skip_ids):
        log(f"action: skip episode {eid} (excluded this pass)")
    return skip_ids


def upload_srt(cfg, series_id, ep_id, lang, srt_bytes, filename="sub.srt"):
    """Manual upload via POST /api/episodes/subtitles (verified against live
    Bazarr swagger.json 2026-08-07): query seriesid/episodeid/language/
    forced/hi + multipart file. Movies use POST /api/movies/subtitles
    (radarrid) — not used (Sonarr-only pipeline). Bazarr ignores the uploaded
    filename (subliminal writes {video stem}.{lang alpha2}.srt), and the
    endpoint has no comment/history field, so AI provenance lives only in the
    first SRT cue."""
    url = cfg["BAZARR_URL"].rstrip("/") + "/episodes/subtitles"
    params = {
        "seriesid": series_id,
        "episodeid": ep_id,
        "language": lang,
        "forced": "false",
        "hi": "false",
    }
    headers = {"X-API-KEY": cfg["BAZARR_API_KEY"]}
    files = {"file": (filename, srt_bytes, "application/x-subrip")}
    last_code = None
    for attempt in range(3):
        try:
            r = requests.post(
                url, params=params, headers=headers, files=files, timeout=120
            )
            last_code = r.status_code
            if r.status_code == 204:
                return 204
            log(
                f"    [upload] HTTP {r.status_code} (attempt {attempt + 1}): {r.text[:200]}"
            )
        except requests.RequestException as exc:
            last_code = None
            log(f"    [upload] network error (attempt {attempt + 1}): {exc}")
        if attempt < 2:
            time.sleep(5 * (attempt + 1))
    return last_code


def notify_hermes(cfg, ep_id, lang, series, tag, exc):
    global _GLOBAL_HELP_LAST
    try:
        url = cfg.get("HERMES_WEBHOOK_URL", "")
        secret = cfg.get("HERMES_WEBHOOK_SECRET", "")
        if not url or not secret:
            return
        now = time.time()
        last = _HELP_COOLDOWN.get((ep_id, lang), 0)
        if now - last < 1800:
            return
        if now - _GLOBAL_HELP_LAST < 600:
            log("help: throttled (global)")
            return
        payload = {
            "event_type": "pipeline_error",
            "episode": f"{tag} {series}",
            "lang": lang,
            "error": str(exc)[:500],
            "log_tail": list(_LOG_RING),
        }
        body = json.dumps(payload).encode()
        ts = str(int(time.time()))
        sig = hmac.new(
            secret.encode(), ts.encode() + b"." + body, hashlib.sha256
        ).hexdigest()
        headers = {
            "X-Webhook-Signature-V2": sig,
            "X-Webhook-Timestamp": ts,
            "Content-Type": "application/json",
        }
        r = requests.post(url, data=body, headers=headers, timeout=10)
        if r.status_code in (200, 202):
            _HELP_COOLDOWN[(ep_id, lang)] = time.time()
            _GLOBAL_HELP_LAST = time.time()
            log(f"help: {tag} {series} [{lang}] notified Hermes")
        else:
            log(f"help: notify failed: HTTP {r.status_code}")
    except Exception as e:
        log(f"help: notify failed: {e}")


def process_after_asr(
    cfg,
    key,
    ep_id,
    lang,
    series,
    tag,
    src,
    t0,
    cues,
    decision,
    info,
    wav_path,
    srt_path,
    prior_cache=None,
):
    global _paused
    try:
        if decision["needs_translate"]:
            t_tr = time.time()
            if not key and not is_local_translate(cfg):
                raise RuntimeError("translate needed but TRANSLATE_API_KEY empty")
            groups = translate_texts(
                cfg,
                cues,
                lang,
                key,
                info.get("seriesId") or info.get("sonarrSeriesId"),
                ep_id,
                prior_cache,
                series_title=series,
            )
            if groups is None:
                raise RuntimeError("translation failed")
            cues_out = []
            texts_out = []
            for s, e, t in groups:
                cues_out.append({"start": cues[s]["start"], "end": cues[e - 1]["end"]})
                texts_out.append(t)
            tr_elapsed = time.time() - t_tr
            log(
                f"  {tag} [{src}->{lang}] translate {tr_elapsed:.0f}s, {len(texts_out)} lines"
            )
        else:
            cues_out = cues
            texts_out = [c["text"] for c in cues]

        write_srt(cues_out, texts_out, srt_path, header=AI_MARKER)
        with open(srt_path, "rb") as fh:
            srt_bytes = fh.read()
        code = upload_srt(
            cfg,
            info.get("seriesId") or info.get("sonarrSeriesId"),
            ep_id,
            lang,
            srt_bytes,
            filename=os.path.basename(srt_path),
        )
        if code != 204:
            raise RuntimeError(f"upload HTTP {code} (expected 204)")
        ef = info.get("episodeFile") or {}
        if ef.get("path"):
            jellyfin_refresh(cfg, map_path(ef["path"]), info.get("title") or info.get("Name"))
        elapsed = round(time.time() - t0, 1)
        append_state(
            {
                "sonarrEpisodeId": ep_id,
                "language": lang,
                "status": "done",
                "elapsed_s": elapsed,
            }
        )
        log(f"done: {tag} {series} [{src}->{lang}] in {elapsed}s (upload 204)")
        return "done"
    except Exception as exc:
        append_state(
            {
                "sonarrEpisodeId": ep_id,
                "language": lang,
                "status": "error",
                "elapsed_s": round(time.time() - t0, 1),
            }
        )
        log(f"fail: {series} [{lang}] {exc}")
        notify_hermes(cfg, ep_id, lang, series, tag, exc)
        halt_on_error(cfg, "process_episode", f"{series} [{lang}] {tag}", exc)
        return "failed"
    finally:
        for f in (wav_path, srt_path):
            try:
                os.remove(f)
            except OSError:
                pass


# ---------- main ----------


def halt_on_error(cfg, stage, ep_desc, exc, extra=None):
    global _paused
    _paused = True
    rep = {
        "ts": time.strftime("%Y-%m-%d %H:%M:%S"),
        "stage": stage,
        "episode": ep_desc,
        "error": str(exc)[:500] or type(exc).__name__,
        "extra": extra or {},
    }
    report_dir = os.path.join(os.path.expanduser("~"), ".config", "asr-pipeline")
    os.makedirs(report_dir, exist_ok=True)
    dst = os.path.join(report_dir, "last_error.json")
    tmp = dst + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(rep, fh, indent=2)
    os.replace(tmp, dst)
    try:
        hist = os.path.join(report_dir, "error_history")
        os.makedirs(hist, exist_ok=True)
        import shutil

        shutil.copy2(
            dst, os.path.join(hist, f"error_{time.strftime('%Y%m%d_%H%M%S')}.json")
        )
    except Exception:
        pass
    log(
        f"[pipeline] PAUSED on error - fix first, resume via pctl resume (report: {dst})"
    )


def run_pass():
    global _paused
    cfg = load_config()
    target_langs = set(cfg["TARGET_LANGS"])
    key = cfg.get("TRANSLATE_API_KEY", "")
    if not key:
        log(
            "WARNING: TRANSLATE_API_KEY is empty; any episode needing translation will FAIL"
        )

    pending_skip = consume_actions(cfg)

    entries = load_state()
    consec_errors = {}
    last_entry = {}
    for e in entries:
        k = (e.get("sonarrEpisodeId"), e.get("language"))
        last_entry[k] = e
        if e.get("status") == "error":
            consec_errors[k] = consec_errors.get(k, 0) + 1
        else:
            consec_errors[k] = 0
    done_keys = {k for k, e in last_entry.items() if e.get("status") == "done"}

    try:
        wanted = get_wanted(cfg)
    except Exception as exc:
        log(f"ERROR fetching wanted list: {exc}")
        return {"fetch_error": True}
    total = wanted.get("total", 0)
    wanted_before = total

    candidates = []
    seen = set()
    for item in wanted.get("data", []):
        ep_id = item.get("sonarrEpisodeId")
        if ep_id in seen:
            continue
        missing = {m.get("code2") for m in item.get("missing_subtitles", [])}
        if missing & target_langs:
            candidates.append(item)
            seen.add(ep_id)
    excluded = parse_exclusions().union(pending_skip)
    if excluded:
        before = len(candidates)
        candidates = [
            it for it in candidates if it.get("sonarrEpisodeId") not in excluded
        ]
        log(f"excluded this pass: {len(before) - len(candidates)} of {before} episodes {sorted(excluded)}")
    candidates.sort(key=lambda x: x["sonarrEpisodeId"])
    candidates = candidates[: cfg["MAX_EPS_PER_RUN"]]
    wanted_now = {it["sonarrEpisodeId"] for it in candidates}

    processed = done = skipped = failed = 0
    log(
        f"wanted total={total}, candidates for pass={len(candidates)} "
        f"(max={cfg['MAX_EPS_PER_RUN']})"
    )

    prior_cache = {}
    futures = []
    # 1 worker is intentional: ASR is VRAM-bound (faster-whisper/SenseVoice
    # model + llama-server share one GPU); serial keeps GPU memory
    # deterministic and avoids OOM under concurrent ASR loads.
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        for item in candidates:
            ep_id = item["sonarrEpisodeId"]
            series = item.get("seriesTitle", "?")
            missing = {m.get("code2") for m in item.get("missing_subtitles", [])}
            langs = sorted(missing & target_langs)
            for lang in langs:
                if (ep_id, lang) in done_keys and ep_id not in wanted_now:
                    log(f"skip: S?E? {series} [{lang}] already done (state)")
                    skipped += 1
                    continue
                if consec_errors.get((ep_id, lang), 0) >= 2:
                    le = last_entry.get((ep_id, lang)) or {}
                    last_ts = le.get("ts", "")
                    try:
                        last_dt = datetime.fromisoformat(last_ts.replace("Z", "+00:00"))
                        age_s = (datetime.now(timezone.utc) - last_dt).total_seconds()
                    except Exception:
                        age_s = 0
                    if age_s < 1800:
                        log(
                            f"park: {series} [{lang}] parked 30min after consecutive errors"
                        )
                        skipped += 1
                        continue
                processed += 1
                t0 = time.time()
                wav_path = srt_path = ""
                try:
                    info = get_episode(cfg, ep_id)
                    season = info.get("seasonNumber", "?")
                    episode_num = info.get("episodeNumber", "?")
                    tag = (
                        f"S{season:02d}E{episode_num:02d}"
                        if isinstance(season, int) and isinstance(episode_num, int)
                        else f"S{season}E{episode_num}"
                    )
                    ef = info.get("episodeFile") or {}
                    if not info.get("hasFile") or not ef.get("path"):
                        log(f"skip: {tag} {series} [{lang}] hasFile=false or no path")
                        skipped += 1
                        continue
                    container_path = ef["path"]
                    media_path = map_path(container_path)
                    if not os.path.isfile(media_path):
                        log(
                            f"skip: {tag} {series} [{lang}] file missing on NFS: {media_path}"
                        )
                        skipped += 1
                        continue
                    streams = probe_audio(media_path)
                    decision = choose_source(streams, lang)
                    if decision is None:
                        log(f"fail: {tag} {series} [{lang}] no audio streams")
                        notify_hermes(
                            cfg,
                            ep_id,
                            lang,
                            series,
                            tag,
                            RuntimeError("no audio streams"),
                        )
                        halt_on_error(
                            cfg,
                            "no_audio_streams",
                            f"{series} [{lang}] {tag}",
                            RuntimeError("no audio streams"),
                        )
                        failed += 1
                        append_state(
                            {
                                "sonarrEpisodeId": ep_id,
                                "language": lang,
                                "status": "error",
                                "elapsed_s": round(time.time() - t0, 1),
                            }
                        )
                        continue
                    src = decision["src_lang"]
                    log(
                        f"proc: {tag} {series} [{src}->{lang}] source_stream={decision['stream_index']} asr_lang={decision['asr_lang']} needs_translate={decision['needs_translate']}"
                    )

                    os.makedirs(cfg["TMP_DIR"], exist_ok=True)
                    wav_path = os.path.join(cfg["TMP_DIR"], f"{ep_id}_{lang}.wav")
                    srt_path = os.path.join(cfg["TMP_DIR"], f"{ep_id}_{lang}.srt")

                    cached_cues = asr_cache_get(ep_id, decision["asr_lang"], media_path)
                    if cached_cues:
                        cues = cached_cues
                        log(f"  {tag} [{src}->{lang}] ASR cache hit (skip extract+asr)")
                    else:
                        extract_wav(media_path, decision["stream_index"], wav_path)
                        t_asr = time.time()
                        cues = asr_cues(cfg, wav_path, decision["asr_lang"])
                        asr_elapsed = time.time() - t_asr
                        asr_cache_put(ep_id, decision["asr_lang"], media_path, cues)
                    cues = [c for c in cues if c["text"].strip()]
                    if not cues:
                        raise RuntimeError("ASR returned no cues")
                    if not cached_cues:
                        log(
                            f"  {tag} [{src}->{lang}] ASR {asr_elapsed:.0f}s, {len(cues)} cues"
                        )
                    futures.append(
                        pool.submit(
                            process_after_asr,
                            cfg,
                            key,
                            ep_id,
                            lang,
                            series,
                            tag,
                            src,
                            t0,
                            cues,
                            decision,
                            info,
                            wav_path,
                            srt_path,
                            prior_cache=prior_cache,
                        )
                    )
                except Exception as exc:
                    failed += 1
                    for f in (wav_path, srt_path):
                        if f:
                            try:
                                os.remove(f)
                            except OSError:
                                pass
                    append_state(
                        {
                            "sonarrEpisodeId": ep_id,
                            "language": lang,
                            "status": "error",
                            "elapsed_s": round(time.time() - t0, 1),
                        }
                    )
                    log(f"fail: {series} [{lang}] {exc}")
                    notify_hermes(cfg, ep_id, lang, series, tag, exc)
                    halt_on_error(
                        cfg, "process_submit", f"{series} [{lang}] {tag}", exc
                    )

        for fut in as_completed(futures):
            if fut.result() == "done":
                done += 1
            else:
                failed += 1

    if processed == 0:
        wanted_after = wanted_before  # nothing changed; skip redundant API call
    else:
        try:
            wanted_after = get_wanted(cfg).get("total", 0)
        except Exception:
            wanted_after = None
    log(
        f"pass summary: processed={processed} done={done} skipped={skipped} failed={failed} "
        f"wanted_before={wanted_before} wanted_after={wanted_after}"
    )
    return {
        "processed": processed,
        "done": done,
        "skipped": skipped,
        "failed": failed,
        "wanted_before": wanted_before,
        "wanted_after": wanted_after,
    }


SECRET_KEY_HINTS = ("KEY", "TOKEN", "SECRET", "PASSWORD")


def _mask_secrets(cfg):
    return {
        k: ("***" if any(h in k.upper() for h in SECRET_KEY_HINTS) else v)
        for k, v in cfg.items()
    }


def _read_overrides():
    if not os.path.exists(OVERRIDE_FILE):
        return {}
    try:
        with open(OVERRIDE_FILE, "r", encoding="utf-8") as fh:
            data = json.loads(fh.read())
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _write_overrides(ov):
    os.makedirs(os.path.dirname(OVERRIDE_FILE), exist_ok=True)
    tmp = OVERRIDE_FILE + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(json.dumps(ov, ensure_ascii=False, indent=2) + "\n")
    os.replace(tmp, OVERRIDE_FILE)


class ControlHandler(BaseHTTPRequestHandler):
    def _send_json(self, code, obj):
        body = json.dumps(obj, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _check_auth(self):
        if not CONTROL_API_KEY:
            self._send_json(401, {"error": "CONTROL_API_KEY not configured"})
            return False
        if self.headers.get("X-API-Key") != CONTROL_API_KEY:
            self._send_json(401, {"error": "unauthorized"})
            return False
        return True

    def _state_counts(self):
        # Count the LATEST entry per (sonarrEpisodeId, language): state.jsonl
        # is append-only, every failed attempt adds a row, so summing every row
        # would report lifetime error counts instead of current state.
        latest = {}
        for e in load_state():
            key = (e.get("sonarrEpisodeId"), e.get("language"))
            cur = latest.get(key)
            if cur is None or (e.get("ts") or "") >= (cur.get("ts") or ""):
                latest[key] = e
        counts = {"done": 0, "error": 0, "pending": 0, "total": len(latest)}
        for e in latest.values():
            st = e.get("status")
            if st == "done" or st == "error":
                counts[st] += 1
            else:
                counts["pending"] += 1
        return counts

    def do_GET(self):
        path = self.path.split("?", 1)[0]
        if path == "/health":
            self._send_json(200, {"ok": True})
        elif path == "/status":
            self._send_json(
                200,
                {
                    "uptime_s": int(
                        (datetime.now(timezone.utc) - _started_at).total_seconds()
                    ),
                    "paused": _paused,
                    "run_once_requested": _run_once_requested,
                    "last_pass": _last_pass_stats,
                    "state_counts": self._state_counts(),
                    "consecutive_failures": _consecutive_failures,
                    "started_at": _started_at.isoformat(),
                },
            )
        elif path == "/config":
            self._send_json(200, _mask_secrets(load_config()))
        elif path == "/sonarr-webhook":
            WAKE_EVENT.set()
            self._send_json(200, {"ok": True})
        else:
            self._send_json(404, {"error": "not found"})

    def do_POST(self):
        global _paused, _run_once_requested
        path = self.path.split("?", 1)[0]
        if path == "/sonarr-webhook":
            WAKE_EVENT.set()
            self._send_json(200, {"ok": True})
            return
        if path == "/wake":
            WAKE_EVENT.set()
            self._send_json(200, {"ok": True})
            return
        if not self._check_auth():
            return
        if path == "/config":
            try:
                raw = self.rfile.read(int(self.headers.get("Content-Length", "0")))
                body = json.loads(raw.decode("utf-8") or "{}")
            except Exception as exc:
                self._send_json(400, {"error": f"invalid JSON body: {exc}"})
                return
            if not isinstance(body, dict):
                self._send_json(400, {"error": "body must be a JSON object"})
                return
            ov = _read_overrides()
            applied = {}
            for k, v in body.items():
                if v is None:
                    ov.pop(k, None)
                    applied[k] = None
                else:
                    ov[str(k)] = str(v)
                    applied[str(k)] = str(v)
            _write_overrides(ov)
            WAKE_EVENT.set()
            self._send_json(200, {"ok": True, "applied": _mask_secrets(applied)})
        elif path == "/pause":
            _paused = True
            self._send_json(200, {"ok": True, "paused": True})
        elif path == "/resume":
            _paused = False
            WAKE_EVENT.set()
            try:
                report_dir = os.path.join(
                    os.path.expanduser("~"), ".config", "asr-pipeline"
                )
                dst = os.path.join(report_dir, "last_error.json")
                if os.path.exists(dst):
                    hist = os.path.join(report_dir, "error_history")
                    os.makedirs(hist, exist_ok=True)
                    os.replace(
                        dst,
                        os.path.join(
                            hist, f"error_{time.strftime('%Y%m%d_%H%M%S')}.json"
                        ),
                    )
                    log("cleared error report")
            except Exception:
                pass
            self._send_json(200, {"ok": True, "paused": False})
        elif path == "/run-once":
            _run_once_requested = True
            WAKE_EVENT.set()
            self._send_json(200, {"ok": True, "run_once_requested": True})
        else:
            self._send_json(404, {"error": "not found"})

    def log_message(self, *args):
        pass


def start_webhook_listener():
    try:
        srv = ThreadingHTTPServer(("0.0.0.0", WEBHOOK_PORT), ControlHandler)
    except OSError as exc:
        log(
            f"webhook listener unavailable on :{WEBHOOK_PORT} ({exc}); continuing without it"
        )
        return
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    log(
        f"control API + webhook listener on :{WEBHOOK_PORT} (GET /status, /config, /health; POST /config /pause /resume /run-once /wake /sonarr-webhook)"
    )


def main():
    lock_path = "/home/user/.config/asr-pipeline/orchestrator.lock"
    lock_fd = open(lock_path, "w")
    try:
        fcntl.flock(lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        log("another orchestrator instance running, exiting")
        return 0
    global _consecutive_failures, _last_pass_stats, _paused, _run_once_requested
    cfg = load_config()
    start_webhook_listener()
    signal.signal(signal.SIGTERM, _handle_sigterm)
    _consecutive_failures = 0
    # startup orphan GC: prune ghost/fileless state rows before the first pass
    try:
        gc_state(cfg, load_state())
    except Exception as exc:
        log(f"GC error at startup: {exc}")
    while True:
        if _paused and not _run_once_requested:
            if _stop_requested:
                log("stop requested while paused; exiting")
                return 0
            log("paused; waiting")
            WAKE_EVENT.wait(timeout=900)
            WAKE_EVENT.clear()
            continue
        try:
            stats = run_pass()
        except Exception as exc:
            halt_on_error(cfg, "pass", "run_pass", exc)
            stats = {"fetch_error": True}
        _last_pass_stats = stats
        _run_once_requested = False
        if _stop_requested:
            log("stop requested, exiting after pass")
            return 0
        if stats.get("fetch_error"):
            _consecutive_failures += 1
        else:
            _consecutive_failures = 0
        remaining = stats.get("wanted_after")
        if remaining is None:
            remaining = stats.get("wanted_before", 0)
        processed = stats.get("processed") or 0
        failed = stats.get("failed") or 0
        busy = (processed > 0 and (remaining or 0) > 0) or failed > 0
        # idle pass (nothing processed): sweep orphan GC for episode ids not
        # yet checked this daemon lifetime; Sonarr down => logged, retried next
        if processed == 0 and not _stop_requested:
            try:
                gc_state(cfg, load_state())
            except Exception as exc:
                log(f"GC error after idle pass: {exc}")
        if _consecutive_failures >= 3:
            delay = 900  # Bazarr/API down - stop hot-looping
        elif busy:
            delay = 60  # backlog or failures - re-check soon
        else:
            delay = 900  # idle
        log(
            f"sleeping {delay}s until next pass (busy={busy}, consecutive_failures={_consecutive_failures})"
        )
        WAKE_EVENT.wait(timeout=delay)
        WAKE_EVENT.clear()


if __name__ == "__main__":
    sys.exit(main())
