import json
import os
import tempfile
import unittest
from unittest.mock import patch

from tests import HermeticStateMixin

import orchestrator as o


class TestRegistryTargetProvenance(HermeticStateMixin):
    def setUp(self):
        super().setUp()
        self.tmp = tempfile.mkdtemp(prefix="asrsub-target-provenance-")
        self.registry = os.path.join(self.tmp, "registry.jsonl")

    def _sidecars(self):
        media = os.path.join(self.tmp, "Show.mkv")
        source = os.path.join(self.tmp, "Show.jpn.srt")
        target = os.path.join(self.tmp, "Show.id.hi.srt")
        open(media, "wb").close()
        with open(source, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:00,000 --> 00:00:01,000\nJapanese source\n")
        with open(target, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:00,000 --> 00:00:01,000\n" + o.AI_MARKER + "\nIndonesian target\n")
        return media, source, target

    def test_process_ladder_records_source_and_target_provenance(self):
        media, source_path, _unused_target = self._sidecars()
        stem = os.path.splitext(media)[0]
        source_hash = o.file_sha256(source_path)
        source = {
            "kind": "jpn",
            "source_path": source_path,
            "source_hash": source_hash,
            "cues": [{"start": 0, "end": 1000, "text": "Japanese source"}],
            "tmp": False,
        }
        info = {"episodeFile": {"path": media}, "seriesId": 4, "title": "Show"}
        cfg = {"TMP_DIR": self.tmp, "TARGET_LANGS": ["id"]}
        with patch.object(o, "REGISTRY_FILE", self.registry), patch.object(
            o, "translate_texts", return_value=[(0, 1, "Indonesian target")]
        ), patch.object(o, "upload_srt", return_value=204), patch.object(
            o, "jellyfin_refresh"
        ), patch.object(o, "notify_webhook"), patch.object(o, "append_state"):
            result = o.process_ladder(
                cfg, "key", 12, "id", "Show", "S01E01", source, info
            )
        self.assertEqual(result, "done")
        target_path = f"{stem}.id.hi.srt"
        self.assertTrue(os.path.isfile(target_path))
        rows = [json.loads(line) for line in open(self.registry, encoding="utf-8")]
        target_row = rows[-1]
        self.assertEqual(target_row["lang"], "id")
        self.assertEqual(target_row["source_path"], source_path)
        self.assertEqual(target_row["source_hash"], source_hash)
        self.assertEqual(target_row["target_path"], target_path)
        self.assertEqual(target_row["target_hash"], o.file_sha256(target_path))

    def test_registry_current_row_validates_source_and_target_hashes(self):
        media, source_path, target_path = self._sidecars()
        stem = os.path.splitext(media)[0]
        row = {
            "stem": stem,
            "lang": "id",
            "source": "jpn",
            "source_kind": "external",
            "source_path": source_path,
            "source_hash": o.file_sha256(source_path),
            "target_path": target_path,
            "target_hash": o.file_sha256(target_path),
        }
        self.assertIsNotNone(
            o._registry_current_row(stem, "id", media_path=media, row=row)
        )
        row["target_hash"] = "stale"
        self.assertIsNone(
            o._registry_current_row(stem, "id", media_path=media, row=row)
        )

    def test_source_alias_path_is_not_a_missing_target_source(self):
        media, source_path, target_path = self._sidecars()
        stem = os.path.splitext(media)[0]
        with open(target_path, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:00,000 --> 00:00:01,000\nAI-generated by ASRSub\nIndonesian target\n")
        row = {
            "stem": stem,
            "lang": "id",
            "source": "jpn",
            "source_kind": "external",
            "source_path": source_path,
            "source_hash": o.file_sha256(source_path),
            "target_path": target_path,
            "target_hash": o.file_sha256(target_path),
        }
        registry = {(stem, "id"): row}
        self.assertIsNotNone(
            o._registry_current_row(stem, "id", media_path=media, row=row)
        )
        self.assertTrue(o.sub_is_ai_owned(registry, 12, "id", media))


if __name__ == "__main__":
    unittest.main()
