import json
import os
import tempfile
import unittest

from tests import HermeticStateMixin

import orchestrator as o


class TestLegacyTranslatedTargetGuard(HermeticStateMixin):
    def test_source_sidecar_is_not_target_output_without_target_file(self):
        tmp = tempfile.mkdtemp(prefix="asrsub-legacy-target-")
        self.addCleanup(lambda: __import__("shutil").rmtree(tmp, ignore_errors=True))
        media = os.path.join(tmp, "Show.mkv")
        source = os.path.join(tmp, "Show.jpn.srt")
        registry = os.path.join(tmp, "registry.jsonl")
        open(media, "wb").close()
        with open(source, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:00,000 --> 00:00:01,000\nJapanese source\n")
        row = {
            "stem": os.path.splitext(media)[0],
            "lang": "id",
            "source": "jpn",
            "source_kind": "external",
            "source_path": source,
            "source_hash": o.file_sha256(source),
        }
        with open(registry, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(row) + "\n")

        current = o._registry_current_row(
            os.path.splitext(media)[0], "id", media_path=media, row=row
        )
        self.assertIsNone(current)

        target = os.path.splitext(media)[0] + ".id.srt"
        with open(target, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:00,000 --> 00:00:01,000\nAI-generated by ASRSub\nTarget\n")
        current = o._registry_current_row(
            os.path.splitext(media)[0], "id", media_path=media, row=row
        )
        self.assertIsNotNone(current)


if __name__ == "__main__":
    unittest.main()
