import json
import os
import tempfile
import unittest
from unittest.mock import patch

from tests import HermeticStateMixin

import orchestrator as o


class TestSafeExternalRetiming(unittest.TestCase):
    def _cues(self, count=4, shift=0):
        return [
            {
                "start": i * 2000 + 1000 + shift,
                "end": i * 2000 + 1800 + shift,
                "text": f"line {i} unique",
            }
            for i in range(count)
        ]

    def test_zero_text_anchors_reject_without_order_mapping(self):
        sub = self._cues()
        asr = self._cues(4, shift=500)
        with patch.object(o, "_retime_text_anchors", return_value=[]):
            out, stats = o.retime_external_cues(
                sub,
                asr,
                "jpn",
                20,
                min_anchor_frac=0.5,
                min_anchors=1,
            )
        self.assertIsNone(out)
        self.assertIsNone(stats["method"])
        self.assertEqual(stats["anchors"], 0)
        self.assertIn("no reliable text anchors", stats["reason"])

    def test_sparse_anchors_reject_instead_of_positional_mapping(self):
        sub = self._cues(10)
        asr = self._cues(10, shift=500)
        with patch.object(o, "_retime_text_anchors", return_value=[(0, 0), (9, 9)]):
            out, stats = o.retime_external_cues(
                sub,
                asr,
                "jpn",
                30,
                min_anchor_frac=0.5,
                min_anchors=1,
            )
        self.assertIsNone(out)
        self.assertEqual(stats["method"], "mixed")
        self.assertIn("anchor coverage", stats["reason"])

    def test_reliable_anchors_are_accepted_and_report_effective_quality(self):
        sub = self._cues(4)
        asr = self._cues(4, shift=500)
        with patch.object(o, "_retime_text_anchors", return_value=[(0, 0), (1, 1), (2, 2), (3, 3)]):
            out, stats = o.retime_external_cues(
                sub,
                asr,
                "jpn",
                20,
                min_anchor_frac=0.5,
                min_anchors=2,
            )
        self.assertIsNotNone(out)
        self.assertEqual(stats["method"], "text")
        self.assertEqual(stats["matched_frac"], 1.0)
        self.assertEqual(stats["anchor_p75_residual_ms"], 0.0)
        self.assertEqual([c["start"] for c in out], [1500.0, 3500.0, 5500.0, 7500.0])

    def test_marker_is_preserved_but_excluded_from_retime_stats(self):
        marker = {"start": 0, "end": 1500, "text": "AI-generated by ASRSub"}
        sub = [marker] + self._cues(4)
        asr = self._cues(4, shift=500)
        with patch.object(o, "_retime_text_anchors", return_value=[(0, 0), (1, 1), (2, 2), (3, 3)]):
            out, stats = o.retime_external_cues(
                sub,
                asr,
                "jpn",
                20,
                min_anchor_frac=0.5,
                min_anchors=2,
            )
        self.assertIsNotNone(out)
        self.assertEqual(out[0], marker)
        self.assertEqual(stats["total"], 4)
        self.assertEqual(stats["anchors"], 4)


class TestEffectiveTimelineProvenance(HermeticStateMixin):
    def setUp(self):
        super().setUp()
        self.tmp = tempfile.mkdtemp()
        self.registry = os.path.join(self.tmp, "registry.jsonl")
        self.video = os.path.join(self.tmp, "episode.mkv")
        self.cfg = {"TARGET_LANGS": ["ja", "id", "en"], "TMP_DIR": self.tmp}
        open(self.video, "wb").close()
        self.stem = os.path.splitext(self.video)[0]
        self.source = self.stem + ".ja.srt"
        with open(self.source, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:01,000 --> 00:00:02,000\nテスト\n\n")
        self.raw = [{"start": 1000, "end": 2000, "text": "テスト"}]
        self.effective = [{"start": 1500, "end": 2500, "text": "テスト"}]

    def test_accepted_retime_stores_raw_and_effective_timeline(self):
        with patch.object(o, "REGISTRY_FILE", self.registry), patch.object(
            o, "probe_audio", return_value=[]
        ), patch.object(o, "audio_stream_signature", return_value="audio"):
            o._register_external_sidecar(
                self.stem,
                "jpn",
                self.video,
                self.source,
                o.file_sha256(self.source),
                ep_id=7,
                stats={
                    "method": "text",
                    "anchors": 1,
                    "total": 1,
                    "matched_frac": 1.0,
                },
                effective_cues=self.effective,
                timeline_kind="retimed",
                retime_status="accepted",
            )
            row = o.registry_get(self.stem, "jpn")
        self.assertEqual(row["source_hash"], o.file_sha256(self.source))
        self.assertEqual(row["timeline_kind"], "retimed")
        self.assertEqual(row["retime_status"], "accepted")
        self.assertEqual(row["retime_policy_version"], o.RETIME_POLICY_VERSION)
        self.assertEqual(row["effective_timeline"], [[1500, 2500]])
        self.assertEqual(
            o._effective_cues_from_row(row, self.raw)[0]["start"],
            1500.0,
        )

    def test_accepted_timeline_is_reused_without_retiming_again(self):
        retimed_path = os.path.join(self.tmp, "retimed.srt")
        with open(retimed_path, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:01,500 --> 00:00:02,500\nテスト\n\n")
        raw_hash = o.file_sha256(self.source)
        raw_verdict = {
            "ok": True,
            "source_hash": raw_hash,
            "cues": self.raw,
        }
        effective_verdict = {
            "ok": True,
            "source_hash": o.file_sha256(retimed_path),
            "cues": self.effective,
        }
        def assess(_cfg, path, _kind, _duration):
            return effective_verdict if path == retimed_path else raw_verdict

        patches = [
            patch.object(o, "REGISTRY_FILE", self.registry),
            patch.object(o, "assess_source_file", side_effect=assess),
            patch.object(o, "_adopt_embedded", return_value=False),
            patch.object(o, "probe_audio", return_value=[]),
            patch.object(o, "audio_stream_signature", return_value="audio"),
        ]
        retime = patch.object(
            o,
            "retime_external_subtitle",
            return_value=(
                retimed_path,
                {
                    "method": "text",
                    "anchors": 1,
                    "total": 1,
                    "matched_frac": 1.0,
                    "retime_status": "accepted",
                },
            ),
        )
        patches.append(retime)
        retime_mock = retime.start()
        for p in patches[:-1]:
            p.start()
        try:
            first = o.detect_ladder_source(self.cfg, self.video, "id", self.tmp, ep_id=7)
            self.assertEqual(first["timeline_kind"], "retimed")
            self.assertEqual(first["cues"][0]["start"], 1500)
            retime_mock.side_effect = AssertionError("stored effective timeline must be reused")
            second = o.detect_ladder_source(self.cfg, self.video, "id", self.tmp, ep_id=7)
        finally:
            for p in patches:
                p.stop()
            o._silent_remove(retimed_path)
        self.assertEqual(second["timeline_kind"], "retimed")
        self.assertEqual(second["cues"][0]["start"], 1500.0)
        self.assertEqual(retime_mock.call_count, 1)

    def test_legacy_retimed_row_is_not_trusted_as_effective(self):
        row = {
            "source_kind": "external",
            "retimed": "mixed",
            "source_hash": "h",
        }
        self.assertIsNone(o._effective_cues_from_row(row, self.raw))

    def test_structurally_bad_raw_external_source_is_not_used(self):
        patches = [
            patch.object(o, "REGISTRY_FILE", self.registry),
            patch.object(
                o,
                "assess_source_file",
                return_value={"ok": True, "source_hash": o.file_sha256(self.source), "cues": self.raw},
            ),
            patch.object(o, "_sidecar_trusted", return_value=False),
            patch.object(o, "_adopt_embedded", return_value=False),
            patch.object(o, "extract_embedded_subtitle", return_value=False),
            patch.object(o, "bazarr_jpn_candidate", return_value=None),
            patch.object(o, "jimaku_direct_candidate", return_value=None),
            patch.object(o, "probe_audio", return_value=[]),
        ]
        timeline_gate = patch.object(
            o, "validate_srt_timeline", return_value=(False, "cue pileup")
        )
        patches.append(timeline_gate)
        timeline_mock = timeline_gate.start()
        for p in patches[:-1]:
            p.start()
        try:
            hit = o.detect_ladder_source(self.cfg, self.video, "id", self.tmp, ep_id=7)
        finally:
            for p in patches:
                p.stop()
        self.assertEqual(hit["kind"], "asr")
        self.assertTrue(timeline_mock.called)

    def test_japanese_target_keeps_raw_external_source_timing(self):
        raw_hash = o.file_sha256(self.source)
        with patch.object(o, "REGISTRY_FILE", self.registry), patch.object(
            o, "probe_audio", return_value=[]
        ), patch.object(o, "audio_stream_signature", return_value="audio"):
            o._register_external_sidecar(
                self.stem,
                "jpn",
                self.video,
                self.source,
                raw_hash,
                effective_cues=self.effective,
                timeline_kind="retimed",
                retime_status="accepted",
            )
            retime = patch.object(
                o,
                "retime_external_subtitle",
                side_effect=AssertionError("Japanese source target must not retime"),
            )
            with patch.object(
                o,
                "assess_source_file",
                return_value={"ok": True, "source_hash": raw_hash, "cues": self.raw},
            ), retime as retime_mock:
                hit = o.detect_ladder_source(self.cfg, self.video, "ja", self.tmp, ep_id=7)
        self.assertEqual(hit["kind"], "jpn")
        self.assertEqual(hit["timeline_kind"], "raw")
        self.assertEqual(hit["cues"][0]["start"], 1000)
        self.assertEqual(o.file_sha256(self.source), raw_hash)
        self.assertEqual(retime_mock.call_count, 0)


        with patch.object(o, "REGISTRY_FILE", self.registry), patch.object(
            o, "probe_audio", return_value=[]
        ), patch.object(o, "audio_stream_signature", return_value="audio"):
            o._register_external_sidecar(
                self.stem,
                "jpn",
                self.video,
                self.source,
                raw_hash,
                effective_cues=self.raw,
                timeline_kind="raw",
                retime_status="rejected",
                retime_reason="no reliable text anchors",
            )
            row = o.registry_get(self.stem, "jpn")
        replay = o._effective_cues_from_row(row, self.raw)
        self.assertEqual(replay[0]["start"], 1000.0)
        self.assertEqual(row["retime_status"], "rejected")


class TestMarkerTimelineGate(HermeticStateMixin):
    def test_marker_does_not_trigger_structural_pileup(self):
        tmp = tempfile.mkdtemp()
        self.addCleanup(lambda: __import__("shutil").rmtree(tmp, ignore_errors=True))
        path = os.path.join(tmp, "marked.srt")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(
                "1\n00:00:00,000 --> 00:00:01,500\nAI-generated by ASRSub\n\n"
                "2\n00:00:02,000 --> 00:00:03,000\n本文\n\n"
                "3\n00:00:04,000 --> 00:00:05,000\n次\n\n"
            )
        ok, why = o.validate_srt_timeline(path, None)
        self.assertTrue(ok, why)


if __name__ == "__main__":
    unittest.main()
