import os
import tempfile
import unittest

import control_api_v2 as api2
import orchestrator as o


class TestLegacyTargetHashFalsePositive(unittest.TestCase):
    def test_stale_target_hash_rejects_legacy_asr_ownership(self):
        with tempfile.TemporaryDirectory(prefix="asrsub-stale-target-hash-") as tmp:
            stem = os.path.join(tmp, "Show")
            media = stem + ".mkv"
            target = stem + ".id.srt"
            open(media, "wb").close()
            with open(target, "w", encoding="utf-8") as fh:
                fh.write("1\n00:00:00,000 --> 00:00:01,000\nAI-generated by ASRSub\nOwned.\n")
            row = {
                "stem": stem, "lang": "id", "source": "asr",
                "source_path": "", "source_hash": "",
                "target_path": target, "target_hash": "stale-hash",
            }
            self.assertIsNone(o._registry_current_row(stem, "id", media_path=media, row=row))
            self.assertFalse(o.sub_is_ai_owned({(stem, "id"): row}, 7, "id", media))
            api = api2.ControlAPIv2({})
            self.assertFalse(api._registry_row_current(row, media, "id"))

            row["target_hash"] = o.file_sha256(target)
            self.assertIsNotNone(o._registry_current_row(stem, "id", media_path=media, row=row))
            self.assertTrue(o.sub_is_ai_owned({(stem, "id"): row}, 7, "id", media))
            self.assertTrue(api._registry_row_current(row, media, "id"))

    def test_absent_registry_read_does_not_create_registry_or_lock(self):
        with tempfile.TemporaryDirectory(prefix="asrsub-read-only-registry-") as tmp:
            registry = os.path.join(tmp, "subtitle_registry.jsonl")
            api = api2.ControlAPIv2({"REGISTRY_FILE": registry})
            self.assertEqual(api._registry(), [])
            self.assertFalse(os.path.exists(registry))
            self.assertFalse(os.path.exists(registry + ".lock"))


if __name__ == "__main__":
    unittest.main()
