import os
import tempfile
import unittest
from unittest.mock import patch

import control_api_v2 as api2
import orchestrator as o


class TestControlApiFalsePositivePaths(unittest.TestCase):
    def test_late_marker_does_not_claim_pathless_asr_row(self):
        with tempfile.TemporaryDirectory(prefix="asrsub-control-late-marker-") as tmp:
            media = os.path.join(tmp, "Show.mkv")
            target = os.path.join(tmp, "Show.id.srt")
            open(media, "wb").close()
            with open(target, "w", encoding="utf-8") as fh:
                fh.write(
                    "1\n00:00:00,000 --> 00:00:01,000\nForeign first.\n\n"
                    "2\n00:00:01,000 --> 00:00:02,000\nAI-generated by ASRSub\n"
                )
            row = {
                "stem": os.path.splitext(media)[0], "lang": "id", "source": "asr",
                "source_path": "", "source_hash": "",
            }
            api = api2.ControlAPIv2({})
            self.assertFalse(api._registry_row_current(row, media, "id"))

            with open(target, "w", encoding="utf-8") as fh:
                fh.write(
                    "1\n00:00:00,000 --> 00:00:01,000\n"
                    "AI-generated by ASRSub\nOwned.\n"
                )
            self.assertTrue(api._registry_row_current(row, media, "id"))

    def test_registry_lang_entries_rejects_stale_row_but_accepts_verified_row(self):
        with tempfile.TemporaryDirectory(prefix="asrsub-control-lang-entries-") as tmp:
            stem = os.path.join(tmp, "Show")
            media = stem + ".mkv"
            target = stem + ".id.srt"
            open(media, "wb").close()
            stale = {
                "stem": stem, "lang": "id", "source": "asr",
                "source_path": "", "source_hash": "",
            }
            api = api2.ControlAPIv2({})
            langs = {}
            api._registry_lang_entries(langs, 7, [stem], {stem: {"id": stale}})
            self.assertNotIn("id", langs.get(7, {}))

            with open(target, "w", encoding="utf-8") as fh:
                fh.write(
                    "1\n00:00:00,000 --> 00:00:01,000\n"
                    "AI-generated by ASRSub\nOwned.\n"
                )
            verified = {
                "stem": stem, "lang": "id", "source": "asr",
                "source_path": target, "source_hash": o.file_sha256(target),
            }
            langs = {}
            api._registry_lang_entries(langs, 7, [stem], {stem: {"id": verified}})
            self.assertEqual(langs[7]["id"]["status"], "done")

    def test_alias_canonicalization_does_not_append_under_shared_lock(self):
        with tempfile.TemporaryDirectory(prefix="asrsub-control-lock-") as tmp:
            media = os.path.join(tmp, "Show.mkv")
            source = os.path.join(tmp, "Show.jpn.srt")
            registry = os.path.join(tmp, "registry.jsonl")
            open(media, "wb").close()
            with open(source, "w", encoding="utf-8") as fh:
                fh.write("1\n00:00:00,000 --> 00:00:01,000\nJapanese.\n")
            row = {
                "stem": os.path.splitext(media)[0], "lang": "jpn", "source": "jpn",
                "source_path": source, "source_hash": o.file_sha256(source),
            }
            with patch.object(o, "REGISTRY_FILE", registry):
                open(registry, "w", encoding="utf-8").close()
                before = open(registry, encoding="utf-8").read()
                with o._registry_lock(registry):
                    o._registry_current_row(
                        os.path.splitext(media)[0], "jpn", media_path=media, row=row
                    )
                self.assertEqual(open(registry, encoding="utf-8").read(), before)


if __name__ == "__main__":
    unittest.main()
