import json
import os
import tempfile
import unittest
from unittest.mock import patch

from tests import HermeticStateMixin

import control_api_v2 as api2
import orchestrator as o


class TestLanguageRegistryAdversarial4(HermeticStateMixin):
    def setUp(self):
        super().setUp()
        self.tmp = tempfile.mkdtemp(prefix="asrsub-adversarial4-")
        self.registry = os.path.join(self.tmp, "registry.jsonl")

    def test_control_state_aliases_collapse_to_latest_canonical_language(self):
        state = os.path.join(self.tmp, "state.jsonl")
        rows = [
            {"kind": "series", "sonarrEpisodeId": 9, "language": "jpn", "status": "error", "ts": "2026-01-01T00:00:00Z"},
            {"kind": "series", "sonarrEpisodeId": 9, "language": "ja", "status": "done", "ts": "2026-01-02T00:00:00Z"},
        ]
        with open(state, "w", encoding="utf-8") as fh:
            for row in rows:
                fh.write(json.dumps(row) + "\n")
        api = api2.ControlAPIv2({"STATE_FILE": state, "REGISTRY_FILE": self.registry})
        _entries, _latest, latest_by_lang = api._state()
        self.assertEqual(set(latest_by_lang), {('series', 9, 'ja')})
        self.assertEqual(latest_by_lang[('series', 9, 'ja')]["status"], "done")

    def test_control_movie_remaining_does_not_trust_pathless_asr_row(self):
        media = os.path.join(self.tmp, "Movie.mkv")
        open(media, "wb").close()
        with open(self.registry, "w", encoding="utf-8") as fh:
            fh.write(json.dumps({
                "stem": os.path.splitext(media)[0], "lang": "ja", "source": "asr",
                "source_path": "", "source_hash": "",
            }) + "\n")
        env = os.path.join(self.tmp, "pipeline.env")
        with open(env, "w", encoding="utf-8") as fh:
            fh.write("TARGET_LANGS=ja\n")
        api = api2.ControlAPIv2({
            "ENV_FILE": env, "OVERRIDE_FILE": os.path.join(self.tmp, "overrides.json"),
            "STATE_FILE": os.path.join(self.tmp, "state.jsonl"),
            "REGISTRY_FILE": self.registry, "NAS_MEDIA_ROOT": self.tmp,
        })
        movies = {"data": [{"radarrId": 4, "path": media, "monitored": True, "missing_subtitles": []}]}
        self.assertEqual(api._movies_remaining_local(movies), 1)

    def test_recalc_does_not_rewrite_foreign_external_jpn_source(self):
        media = os.path.join(self.tmp, "Foreign.mkv")
        canonical = os.path.join(self.tmp, "Foreign.ja.srt")
        foreign = os.path.join(self.tmp, "Foreign.jpn.srt")
        open(media, "wb").close()
        with open(canonical, "wb") as fh:
            fh.write(b"broken-canonical")
        with open(foreign, "wb") as fh:
            fh.write(b"foreign-source")
        digest = o.file_sha256(foreign)
        row = {"stem": os.path.splitext(media)[0], "lang": "jpn", "source": "jpn", "source_kind": "external", "source_path": foreign, "source_hash": digest, "episode_id": 8}
        with open(self.registry, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(row) + "\n")
        before = open(canonical, "rb").read()
        with patch.object(o, "REGISTRY_FILE", self.registry), patch.object(
            o, "validate_srt_timeline", side_effect=[(False, "broken"), (True, "ok")]
        ), patch.object(o, "media_duration_s", return_value=60.0), patch.object(
            o, "probe_audio", return_value=[]
        ), patch.object(o, "audio_stream_signature", return_value="audio"), patch.object(
            o, "asr_cache_get", return_value=[{"start": 0, "end": 1000, "text": "cache"}]
        ):
            result = o.run_timeline_recalc({"TIMELINE_RECALC_BUDGET": 1})
        self.assertEqual(result["repaired"], 0)
        self.assertEqual(open(canonical, "rb").read(), before)
        rows = [json.loads(line) for line in open(self.registry, encoding="utf-8")]
        self.assertEqual(rows, [row])

    def test_recalc_preserves_asr_provenance_for_ai_owned_row(self):
        media = os.path.join(self.tmp, "Owned.mkv")
        canonical = os.path.join(self.tmp, "Owned.ja.hi.srt")
        open(media, "wb").close()
        with open(canonical, "wb") as fh:
            fh.write(b"1\n00:00:00,000 --> 00:00:01,000\nAI-generated by ASRSub\nbroken\n")
        row = {"stem": os.path.splitext(media)[0], "lang": "ja", "source": "asr", "source_kind": "asr", "source_path": canonical, "source_hash": o.file_sha256(canonical), "episode_id": 10}
        with open(self.registry, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(row) + "\n")
        with patch.object(o, "REGISTRY_FILE", self.registry), patch.object(
            o, "validate_srt_timeline", side_effect=[(False, "broken"), (True, "ok")]
        ), patch.object(o, "media_duration_s", return_value=60.0), patch.object(
            o, "probe_audio", return_value=[]
        ), patch.object(o, "audio_stream_signature", return_value="audio"), patch.object(
            o, "asr_cache_get", return_value=[{"start": 0, "end": 1000, "text": "rebuilt"}]
        ):
            result = o.run_timeline_recalc({"TIMELINE_RECALC_BUDGET": 1})
        self.assertEqual(result["repaired"], 1)
        self.assertIn("AI-generated by ASRSub", open(canonical, encoding="utf-8").read())
        rows = [json.loads(line) for line in open(self.registry, encoding="utf-8")]
        self.assertEqual(rows[-1]["source"], "asr")
        self.assertEqual(rows[-1]["source_path"], canonical)
        self.assertIsNone(rows[-1].get("source_kind"))
        self.assertEqual(rows[-1]["source_hash"], o.file_sha256(canonical))


if __name__ == "__main__":
    unittest.main()
