import os
import tempfile
import unittest

from tests import HermeticStateMixin

import control_api_v2 as api2


class TestControlSourceTargetRegistry(HermeticStateMixin):
    def test_current_registry_row_validates_source_and_target_artifacts(self):
        tmp = tempfile.mkdtemp(prefix="asrsub-control-provenance-")
        self.addCleanup(lambda: __import__("shutil").rmtree(tmp, ignore_errors=True))
        media = os.path.join(tmp, "Show.mkv")
        source = os.path.join(tmp, "Show.jpn.srt")
        target = os.path.join(tmp, "Show.id.srt")
        open(media, "wb").close()
        with open(source, "wb") as fh:
            fh.write(b"japanese source")
        with open(target, "wb") as fh:
            fh.write(b"1\n00:00:00,000 --> 00:00:01,000\nAI-generated by ASRSub\nindonesian target\n")
        row = {
            "stem": os.path.splitext(media)[0],
            "lang": "id",
            "source": "jpn",
            "source_kind": "external",
            "source_path": source,
            "source_hash": api2.hashlib.sha256(open(source, "rb").read()).hexdigest(),
            "target_path": target,
            "target_hash": api2.hashlib.sha256(open(target, "rb").read()).hexdigest(),
        }
        api = api2.ControlAPIv2()
        self.assertTrue(api._registry_row_current(row, media, "id"))
        row["target_hash"] = "stale"
        self.assertFalse(api._registry_row_current(row, media, "id"))


if __name__ == "__main__":
    unittest.main()
