import json
import os
import subprocess
import tempfile
import unittest
from unittest.mock import patch

from tests import HermeticStateMixin

import orchestrator as o


class TestLanguageRegistryAdversarial3(HermeticStateMixin):
    def setUp(self):
        super().setUp()
        self.tmp = tempfile.mkdtemp(prefix="asrsub-adversarial3-")
        self.registry = os.path.join(self.tmp, "registry.jsonl")

    def test_sweep_extracts_missing_target_to_canonical_sidecar(self):
        media = os.path.join(self.tmp, "Show.mkv")
        open(media, "wb").close()
        streams = [{
            "index": 7,
            "codec_type": "subtitle",
            "codec_name": "ass",
            "tags": {"language": "jpn"},
        }]
        maps = []

        def fake_run(cmd, **kwargs):
            self.assertEqual(cmd[0], "ffmpeg")
            maps.append(cmd[cmd.index("-map") + 1])
            with open(cmd[-1], "w", encoding="utf-8") as fh:
                fh.write("1\n00:00:00,000 --> 00:00:01,000\nline\n")
            return subprocess.CompletedProcess(cmd, 0, "", "")

        cfg = {"TARGET_LANGS": ["ja"], "JELLYFIN_MEDIA_ROOT": self.tmp}
        real_isdir = o.os.path.isdir

        def isdir(path):
            return False if path == "/mnt/nas/share/media/jellyfin" else real_isdir(path)

        with patch.object(o, "REGISTRY_FILE", self.registry), patch.object(
            o, "_subtitle_streams", return_value=streams
        ), patch.object(o.os.path, "isdir", side_effect=isdir), patch.object(
            o.subprocess, "run", side_effect=fake_run
        ):
            result = o.run_embedded_srt_sweep(cfg, budget=1)

        stem = os.path.splitext(media)[0]
        target = f"{stem}.ja.hi.srt"
        self.assertEqual(result["extracted"], 1)
        self.assertEqual(maps, ["0:7"])
        self.assertTrue(os.path.isfile(target))
        self.assertIn("line", open(target, encoding="utf-8").read())
        rows = [json.loads(line) for line in open(self.registry, encoding="utf-8")]
        self.assertEqual(rows, [{
            **rows[0],
            "lang": "ja",
            "source_path": target,
            "source_hash": o.file_sha256(target),
        }])

    def test_upgrades_consider_legacy_jpn_registry_row_for_ja_target(self):
        media = os.path.join(self.tmp, "Show.mkv")
        sidecar = os.path.join(self.tmp, "Show.ja.srt")
        open(media, "wb").close()
        with open(sidecar, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:00,000 --> 00:00:01,000\nAI-generated by ASRSub\nold\n")
        with open(self.registry, "w", encoding="utf-8") as fh:
            fh.write(json.dumps({
                "stem": os.path.splitext(media)[0], "lang": "jpn", "source": "asr",
                "source_path": sidecar, "source_hash": o.file_sha256(sidecar),
                "episode_id": 7, "updated_ts": "2026-01-01T00:00:00Z",
                "created_ts": "2026-01-01T00:00:00Z",
            }) + "\n")
        info = {"hasFile": True, "episodeFile": {"path": media}, "seriesId": 3, "title": "Show"}
        ladder = {"kind": "jpn", "source_path": sidecar, "source_hash": "new-hash", "cues": [{"start": 0, "end": 1000, "text": "new"}], "effective_timeline": [[0, 1000]], "timeline_kind": "raw", "tmp": False}
        cfg = {"TARGET_LANGS": ["ja"], "LADDER_UPGRADE_BUDGET": 1, "LADDER_COOLDOWN_H": 0, "TMP_DIR": self.tmp}
        with patch.object(o, "REGISTRY_FILE", self.registry), patch.object(
            o, "get_episode", return_value=info
        ), patch.object(o, "detect_ladder_source", return_value=ladder), patch.object(
            o, "process_ladder", return_value="done"
        ) as process:
            result = o.run_upgrades(cfg, "key")
        self.assertEqual(result, {"upgraded": 1, "checked": 1})
        process.assert_called_once()

    def test_ordering_uses_legacy_registry_alias_for_prior_timestamp(self):
        first = os.path.join(self.tmp, "First.mkv")
        second = os.path.join(self.tmp, "Second.mkv")
        open(first, "wb").close()
        open(second, "wb").close()
        os.utime(first, (2000, 2000))
        os.utime(second, (1000, 1000))
        with open(self.registry, "w", encoding="utf-8") as fh:
            fh.write(json.dumps({
                "stem": os.path.splitext(first)[0], "lang": "jpn", "source": "asr",
                "episode_id": 1, "updated_ts": "2026-01-01T00:00:00Z",
            }) + "\n")
        items = [
            {"movie": True, "radarrId": 1, "sonarrEpisodeId": 1, "path": first, "dateAdded": "2026-08-01T00:00:00Z", "missing_subtitles": [{"code2": "ja"}]},
            {"movie": True, "radarrId": 2, "sonarrEpisodeId": 2, "path": second, "missing_subtitles": [{"code2": "ja"}]},
        ]
        cfg = {"TARGET_LANGS": ["ja"]}
        with patch.object(o, "REGISTRY_FILE", self.registry):
            ordered, _ = o._order_pass_candidates(cfg, [], items, [], 2)
        self.assertEqual([item["radarrId"] for item in ordered], [1, 2])


if __name__ == "__main__":
    unittest.main()
