import json
import os
import tempfile
import unittest

import orchestrator as o


class TestRegistryTargetAliasReconciliation(unittest.TestCase):
    def _fixture(self, target_hash=None):
        tmp = tempfile.TemporaryDirectory(prefix="asrsub-target-alias-reconcile-")
        stem = os.path.join(tmp.name, "Show")
        registry = os.path.join(tmp.name, "registry.jsonl")
        source = stem + ".jpn.srt"
        target = stem + ".ind.srt"
        media = stem + ".mkv"
        open(media, "wb").close()
        with open(source, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:00,000 --> 00:00:01,000\nJapanese source.\n")
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(
                "1\n00:00:00,000 --> 00:00:01,000\n"
                "AI-generated by ASRSub\nIndonesian target.\n"
            )
        row = {
            "stem": stem, "lang": "id", "episode_id": 7, "source": "jpn",
            "source_kind": "external", "source_path": source,
            "source_hash": o.file_sha256(source), "target_path": target,
            "target_hash": target_hash if target_hash is not None else o.file_sha256(target),
        }
        with open(registry, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(row) + "\n")
        return tmp, stem, registry, source, target, row

    def test_reconcile_updates_renamed_target_as_canonical_append(self):
        tmp, stem, registry, source, target, row = self._fixture()
        self.addCleanup(tmp.cleanup)
        canonical = stem + ".id.srt"
        os.rename(target, canonical)
        with __import__("unittest").mock.patch.object(o, "REGISTRY_FILE", registry):
            result = o.reconcile_registry(registry, budget=1)
        self.assertEqual(result["reconciled"], 1, result)
        with open(registry, encoding="utf-8") as fh:
            rows = [json.loads(line) for line in fh]
        self.assertEqual(len(rows), 2)
        self.assertEqual(rows[-1]["source_path"], source)
        self.assertEqual(rows[-1]["source_hash"], row["source_hash"])
        self.assertEqual(rows[-1]["target_path"], canonical)
        self.assertEqual(rows[-1]["target_hash"], o.file_sha256(canonical))

    def test_reconcile_rejects_mismatched_target_hash(self):
        tmp, _stem, registry, _source, target, _row = self._fixture("wrong-hash")
        self.addCleanup(tmp.cleanup)
        result = o.reconcile_registry(registry, budget=1)
        self.assertEqual(result["reconciled"], 0, result)
        self.assertEqual(result["invalid"], 1, result)
        with open(registry, encoding="utf-8") as fh:
            self.assertEqual(len(fh.readlines()), 1)


if __name__ == "__main__":
    unittest.main()
