import json
import os
import tempfile
import unittest

from tests import HermeticStateMixin

import orchestrator as o


class TestRegistryReconciliation(HermeticStateMixin):
    def test_reconcile_registry_appends_only_verified_current_rows(self):
        tmp = tempfile.mkdtemp(prefix="asrsub-reconcile-")
        self.addCleanup(lambda: __import__("shutil").rmtree(tmp, ignore_errors=True))
        registry = os.path.join(tmp, "registry.jsonl")
        media = os.path.join(tmp, "Show.mkv")
        embedded = os.path.join(tmp, "Show.jpn.srt")
        target = os.path.join(tmp, "Show.en.srt")
        stale = os.path.join(tmp, "gone.srt")
        open(media, "wb").close()
        with open(embedded, "wb") as fh:
            fh.write(b"embedded japanese")
        with open(target, "w", encoding="utf-8") as fh:
            fh.write("1\n00:00:00,000 --> 00:00:01,000\nAI-generated by ASRSub\nEnglish\n")
        old_rows = [
            {
                "stem": os.path.splitext(media)[0],
                "lang": "jpn",
                "source": "embedded",
                "source_kind": "embedded",
                "source_path": embedded,
                "source_hash": o.file_sha256(embedded),
            },
            {
                "stem": os.path.splitext(media)[0],
                "lang": "enm",
                "source": "asr",
                "source_path": "",
                "source_hash": "",
            },
            {
                "stem": os.path.splitext(media)[0],
                "lang": "jpn",
                "source": "jpn",
                "source_kind": "external",
                "source_path": stale,
                "source_hash": "stale",
            },
        ]
        with open(registry, "w", encoding="utf-8") as fh:
            for row in old_rows:
                fh.write(json.dumps(row) + "\n")

        result = o.reconcile_registry(registry, budget=10)

        with open(registry, encoding="utf-8") as fh:
            rows = [json.loads(line) for line in fh if line.strip()]
        self.assertEqual(len(rows), 5)
        self.assertEqual(rows[:3], old_rows)
        self.assertEqual(result["reconciled"], 2)
        self.assertEqual(result["invalid"], 1)
        self.assertEqual(rows[-2]["lang"], "ja")
        self.assertEqual(rows[-2]["source_path"], embedded)
        self.assertEqual(rows[-2]["source_hash"], o.file_sha256(embedded))
        self.assertEqual(rows[-1]["lang"], "en")
        self.assertEqual(rows[-1]["source"], "asr")
        self.assertEqual(rows[-1]["source_path"], target)
        self.assertEqual(rows[-1]["source_hash"], o.file_sha256(target))
        self.assertEqual(sum(row["source_path"] == stale for row in rows), 1)


    def test_single_valid_legacy_row_is_reconciled_without_duplicate_history(self):
        tmp = tempfile.mkdtemp(prefix="asrsub-reconcile-single-")
        self.addCleanup(lambda: __import__("shutil").rmtree(tmp, ignore_errors=True))
        registry = os.path.join(tmp, "registry.jsonl")
        media = os.path.join(tmp, "Show.mkv")
        sidecar = os.path.join(tmp, "Show.jpn.srt")
        open(media, "wb").close()
        with open(sidecar, "wb") as fh:
            fh.write(b"legacy embedded source")
        old = {
            "stem": os.path.splitext(media)[0],
            "lang": "jpn",
            "source": "embedded",
            "source_kind": "embedded",
            "source_path": sidecar,
            "source_hash": o.file_sha256(sidecar),
        }
        with open(registry, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(old) + "\n")

        result = o.reconcile_registry(registry, budget=1)

        with open(registry, encoding="utf-8") as fh:
            rows = [json.loads(line) for line in fh if line.strip()]
        self.assertEqual(len(rows), 2)
        self.assertEqual(rows[0], old)
        self.assertEqual(result["scanned"], 1)
        self.assertEqual(result["reconciled"], 1)
        self.assertEqual(rows[1]["lang"], "ja")
        self.assertEqual(rows[1]["source"], "embedded")
        self.assertEqual(rows[1]["source_kind"], "embedded")
        self.assertEqual(rows[1]["source_path"], sidecar)
        self.assertEqual(rows[1]["source_hash"], o.file_sha256(sidecar))


if __name__ == "__main__":
    unittest.main()
