//! SRT cue model + post-processing passes.
//!
//! Hot-path code is allocation-conscious: timestamps are `u32` millis,
//! parsing reuses a single pass over the input, and the CPS-merge pass works
//! in place over `Vec<Cue>`: AI-marker first cue, contiguity clamp, CPS
//! reading-speed merge, timeline validation, echo/wrong-script guards.

use anyhow::Result;

pub const AI_MARKER: &str = "[AI-generated by ASRSub]";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Cue {
    pub start_ms: u32,
    pub end_ms: u32,
    pub text: String,
}

impl Cue {
    pub fn new(start_ms: u32, end_ms: u32, text: impl Into<String>) -> Self {
        Self {
            start_ms,
            end_ms,
            text: text.into(),
        }
    }
}

/// `00:00:01,500` <-> millis. Accepts `,` or `.` separators.
pub fn parse_ts(v: &str) -> Option<u32> {
    let v = v.trim();
    let mut it = v.split(':');
    let h: u32 = it.next()?.trim().parse().ok()?;
    let m: u32 = it.next()?.trim().parse().ok()?;
    let rest = it.next()?;
    let (s, ms) = rest.split_once([',', '.'])?;
    let s: u32 = s.trim().parse().ok()?;
    let ms: u32 = format!("{:0<3}", ms.trim())
        .chars()
        .take(3)
        .collect::<String>()
        .parse()
        .ok()?;
    Some(h * 3_600_000 + m * 60_000 + s * 1000 + ms)
}

pub fn fmt_ts(ms: u32) -> String {
    let h = ms / 3_600_000;
    let rem = ms % 3_600_000;
    let m = rem / 60_000;
    let rem = rem % 60_000;
    let s = rem / 1000;
    let msr = rem % 1000;
    format!("{h:02}:{m:02}:{s:02},{msr:03}")
}

fn parse_ts_line(line: &str) -> Option<(u32, u32)> {
    let (a, b) = line.split_once("-->")?;
    Some((parse_ts(a)?, parse_ts(b)?))
}

/// Tolerant SRT parser: skips index lines, tolerates missing numbering and
/// `\r\n`, drops empty bodies. Multi-line bodies collapse with `" "`, so
/// `cps_merge` line-counts and re-read char counts stay consistent on
/// ladder/embedded input.
pub fn parse_srt(text: &str) -> Vec<Cue> {
    let mut cues = Vec::new();
    // Normalize then split on blank lines without allocating per block twice.
    let norm = text.replace("\r\n", "\n");
    for block in norm.split("\n\n") {
        let block = block.trim();
        if block.is_empty() {
            continue;
        }
        let mut start: Option<u32> = None;
        let mut end: Option<u32> = None;
        let mut body: Vec<&str> = Vec::new();
        let mut ts_seen = false;
        for line in block.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            if !ts_seen && line.contains("-->") {
                if let Some((s, e)) = parse_ts_line(line) {
                    start = Some(s);
                    end = Some(e);
                    ts_seen = true;
                }
                continue;
            }
            if ts_seen {
                body.push(line);
            }
            // Lines before the timestamp (numeric index) are ignored.
        }
        if let (Some(s), Some(e)) = (start, end) {
            let text = body.join(" ").trim().to_string();
            if !text.is_empty() {
                cues.push(Cue::new(s, e, text));
            }
        }
    }
    cues
}

/// Serialize cues; when `marker` is true the AI provenance cue becomes a real
/// first cue at 0..1500 ms (bumped before dialogue starting < 2 s).
pub fn write_srt(cues: &[Cue], marker: bool, marker_ms: u32) -> String {
    // Pre-size: ~64 bytes/cue heuristic avoids regrowth on big libraries.
    let mut out = String::with_capacity(cues.len() * 64 + 64);
    let mut idx = 1u32;
    if marker {
        let first_start = cues.iter().map(|c| c.start_ms).min();
        let mut end = marker_ms;
        if let Some(fs) = first_start {
            if fs < 2000 {
                end = fs.saturating_sub(1);
            }
        }
        // Never emit a zero-duration cue: dialogue at t=0 leaves no room, so
        // the marker takes a nominal 1 ms (players skip it either way, and
        // the timeline stays structurally valid).
        end = end.max(1);
        out.push_str(&format!(
            "{idx}\n00:00:00,000 --> {}\n{AI_MARKER}\n\n",
            fmt_ts(end)
        ));
        idx += 1;
    }
    for c in cues {
        out.push_str(&format!(
            "{idx}\n{} --> {}\n{}\n\n",
            fmt_ts(c.start_ms),
            fmt_ts(c.end_ms),
            c.text
        ));
        idx += 1;
    }
    out
}

pub fn write_srt_to(path: &str, cues: &[Cue], marker: bool, marker_ms: u32) -> Result<()> {
    let text = write_srt(cues, marker, marker_ms);
    crate::state::ensure_parent(std::path::Path::new(path))?;
    // Atomic install: tmp + rename so readers never see a half-written sidecar.
    let tmp = format!("{path}.tmp-{}", std::process::id());
    std::fs::write(&tmp, text.as_bytes())?;
    std::fs::rename(&tmp, path)?;
    Ok(())
}

/// Post-pass: never overlap — `next.start = max(next.start, prev.end)`.
pub fn ensure_contiguous(cues: &mut [Cue]) {
    cues.sort_by_key(|c| c.start_ms);
    for i in 1..cues.len() {
        if cues[i].start_ms < cues[i - 1].end_ms {
            cues[i].start_ms = cues[i - 1].end_ms;
        }
        if cues[i].end_ms < cues[i].start_ms {
            cues[i].end_ms = cues[i].start_ms;
        }
    }
}

/// Split over-long cues to `<= max_ms` pieces.
///
/// Whitespace-separated words pack greedily with per-word durations
/// estimated from the span (all counts in chars, never bytes, so multibyte
/// scripts pack correctly); CJK text without spaces splits by chars into
/// `ceil(span/max)` proportional parts.
pub fn split_long_cues(cues: Vec<Cue>, max_ms: u32) -> Vec<Cue> {
    let mut out = Vec::with_capacity(cues.len());
    for c in cues {
        let span = c.end_ms.saturating_sub(c.start_ms);
        if span <= max_ms || c.text.is_empty() {
            out.push(c);
            continue;
        }
        let words: Vec<&str> = c.text.split_whitespace().collect();
        if words.len() < 2 {
            // CJK without spaces: split by chars.
            let chars: Vec<char> = c.text.chars().collect();
            let total = chars.len().max(1);
            let n = span.div_ceil(max_ms).max(2) as usize;
            let per = total.div_ceil(n).max(1);
            for (k, chunk) in chars.chunks(per).enumerate() {
                let lo = (k * per).min(total);
                let hi = ((k + 1) * per).min(total);
                let s = c.start_ms + (span as usize * lo / total) as u32;
                let e = if hi >= total {
                    c.end_ms
                } else {
                    c.start_ms + (span as usize * hi / total) as u32
                };
                out.push(Cue::new(s, e.max(s), chunk.iter().collect::<String>()));
            }
            continue;
        }
        let per_word = span as f64 / words.len() as f64;
        let mut cur: Vec<&str> = Vec::new();
        let mut cur_start = c.start_ms;
        for (wi, w) in words.iter().enumerate() {
            cur.push(w);
            let is_last = wi + 1 == words.len();
            let used = cur.len() as f64 * per_word;
            if (used >= max_ms as f64 || is_last) && !cur.is_empty() {
                let e = if is_last {
                    c.end_ms
                } else {
                    (cur_start + used as u32).min(c.end_ms)
                };
                out.push(Cue::new(cur_start, e.max(cur_start), cur.join(" ")));
                cur = Vec::new();
                cur_start = e;
            }
        }
        if !cur.is_empty() {
            out.push(Cue::new(cur_start, c.end_ms.max(cur_start), cur.join(" ")));
        }
    }
    out
}

/// Reading-speed merge: cues above `max_cps` chain into following cues while
/// every condition holds (gap, chars, duration, 2-line cap). Only applied to
/// ASR-translated output, never to ladder/embedded output.
///
/// Linear time: each cue is visited once and either pushed or folded into
/// the running head (no `Vec::remove` shifting).
pub fn cps_merge(
    cues: Vec<Cue>,
    max_cps: f64,
    max_chars: usize,
    max_dur_ms: u32,
    max_gap_ms: u32,
) -> Vec<Cue> {
    fn cps_of(text: &str, start_ms: u32, end_ms: u32) -> f64 {
        let dur_s = (end_ms as i64 - start_ms as i64) as f64 / 1000.0;
        if dur_s <= 0.0 {
            f64::INFINITY
        } else {
            text.chars().count() as f64 / dur_s
        }
    }
    let mut out: Vec<Cue> = Vec::with_capacity(cues.len());
    let mut iter = cues.into_iter();
    let Some(first) = iter.next() else {
        return out;
    };
    let mut cur = first;
    for nxt in iter {
        // Only a too-fast head absorbs followers; in-limit cues flush through.
        if cps_of(&cur.text, cur.start_ms, cur.end_ms) <= max_cps {
            out.push(std::mem::replace(&mut cur, nxt));
            continue;
        }
        let gap = nxt.start_ms as i64 - cur.end_ms as i64;
        let cur_lines = cur.text.matches('\n').count() + 1;
        let nxt_lines = nxt.text.matches('\n').count() + 1;
        let joined_len = cur.text.chars().count() + 1 + nxt.text.chars().count();
        let sep = if joined_len <= max_chars / 2 {
            " "
        } else {
            "\n"
        };
        let combined = format!("{}{}{}", cur.text, sep, nxt.text);
        let combined_dur_s = (nxt.end_ms as i64 - cur.start_ms as i64) as f64 / 1000.0;
        let fits = gap <= max_gap_ms as i64
            && cur_lines + nxt_lines <= 2
            && joined_len <= max_chars
            && combined_dur_s > 0.0
            && combined.chars().count() as f64 / combined_dur_s <= max_cps
            && combined_dur_s * 1000.0 <= max_dur_ms as f64;
        if fits {
            cur.end_ms = nxt.end_ms;
            cur.text = combined;
        } else {
            out.push(std::mem::replace(&mut cur, nxt));
        }
    }
    out.push(cur);
    out
}

/// Structural timeline gate: per-cue sanity plus file-level checks. Returns
/// human-readable violation strings. Starts
/// must be non-decreasing ("monotonic") with at most `MAX_PILEUP` cues
/// sharing one identical start ("pileup"); with a known video duration the
/// span must cover `MIN_COVERAGE` of it ("coverage") with no single inter-cue
/// gap exceeding `MAX_GAP_FRAC` ("gap"). Thresholds are consts. Returns
/// violation strings; empty means clean.
pub fn validate_timeline(cues: &[Cue], max_cue_ms: u32, duration_s: Option<f64>) -> Vec<String> {
    const MAX_PILEUP: u32 = 2;
    const MIN_COVERAGE: f64 = 0.80;
    const MAX_GAP_FRAC: f64 = 0.30;
    let mut v = Vec::new();
    // The leading AI provenance marker is exempt: it is metadata, not
    // dialogue, and may touch t=0 dialogue by 1 ms when the episode opens
    // on speech (see write_srt's nominal-1 ms clamp).
    let body: &[Cue] = match cues.first() {
        Some(first) if has_ai_marker_text(&first.text) => &cues[1.min(cues.len())..],
        _ => cues,
    };
    if body.is_empty() {
        v.push("no cues".to_string());
        return v;
    }
    let mut pileup: u32 = 1;
    let mut worst_pileup: u32 = 1;
    let mut worst_gap_ms: u32 = 0;
    for (i, c) in body.iter().enumerate() {
        if c.text.trim().is_empty() {
            v.push(format!("cue {i}: empty text"));
        }
        if c.end_ms < c.start_ms {
            v.push(format!("cue {i}: end before start"));
        }
        if c.end_ms - c.start_ms > max_cue_ms {
            v.push(format!(
                "cue {i}: duration {}ms > {max_cue_ms}ms",
                c.end_ms - c.start_ms
            ));
        }
        if i > 0 {
            let prev = &body[i - 1];
            if c.start_ms < prev.start_ms {
                v.push(format!("cue {i}: starts not monotonic"));
            }
            if c.start_ms < prev.end_ms {
                v.push(format!("cue {i}: overlaps previous"));
            }
            if c.start_ms == prev.start_ms {
                pileup += 1;
                worst_pileup = worst_pileup.max(pileup);
            } else {
                pileup = 1;
            }
            worst_gap_ms =
                worst_gap_ms.max(c.start_ms.saturating_sub(prev.end_ms.max(prev.start_ms)));
        }
    }
    if worst_pileup > MAX_PILEUP {
        v.push(format!(
            "cue pileup: {worst_pileup} cues share one start (max {MAX_PILEUP})"
        ));
    }
    if let Some(dur) = duration_s {
        if dur > 0.0 {
            let first_start = body.first().map(|c| c.start_ms).unwrap_or(0);
            let last_end = body.iter().map(|c| c.end_ms).max().unwrap_or(0);
            let span_s = last_end.saturating_sub(first_start) as f64 / 1000.0;
            if span_s / dur < MIN_COVERAGE {
                v.push(format!(
                    "coverage {span_s:.0}s of {dur:.0}s below {:.0}%",
                    MIN_COVERAGE * 100.0
                ));
            }
            if worst_gap_ms as f64 / 1000.0 / dur > MAX_GAP_FRAC {
                v.push(format!(
                    "internal gap {:.0}s exceeds {:.0}% of runtime",
                    worst_gap_ms as f64 / 1000.0,
                    MAX_GAP_FRAC * 100.0
                ));
            }
        }
    }
    v
}

/// Collapse runs of >max_repeat identical chars (anime screams collapse small
/// models); appends an ellipsis marker.
pub fn sanitize_lines(lines: Vec<String>, max_repeat: usize) -> Vec<String> {
    lines
        .into_iter()
        .map(|s| {
            if s.is_empty() {
                return s;
            }
            let mut out = String::with_capacity(s.len());
            let mut chars = s.chars().peekable();
            while let Some(c) = chars.next() {
                let mut run = 1;
                while chars.peek() == Some(&c) {
                    chars.next();
                    run += 1;
                }
                if run > max_repeat {
                    out.extend(std::iter::repeat_n(c, max_repeat));
                    out.push('…');
                } else {
                    out.extend(std::iter::repeat_n(c, run));
                }
            }
            out
        })
        .collect()
}

fn has_kana(s: &str) -> bool {
    s.chars().any(crate::lang::is_kana)
}
fn has_hanzi(s: &str) -> bool {
    s.chars()
        .any(|c| ('\u{3400}'..='\u{4dbf}').contains(&c) || ('\u{4e00}'..='\u{9fff}').contains(&c))
}
fn latin_ratio(s: &str) -> f64 {
    if s.is_empty() {
        return 0.0;
    }
    let latin = s.chars().filter(|c| c.is_ascii_alphabetic()).count();
    latin as f64 / s.chars().count().max(1) as f64
}

/// Foreign-script guard: lines that are hanzi-without-kana or mostly-latin
/// (OP/ED lyrics the ASR echoed in Chinese/English) become SDH placeholders
/// so the translator never echoes the whole chunk.
pub fn guard_foreign_lines(lines: Vec<String>, placeholders: &[String]) -> Vec<String> {
    let mut out = Vec::with_capacity(lines.len());
    for (i, l) in lines.into_iter().enumerate() {
        if (has_hanzi(&l) && !has_kana(&l)) || (latin_ratio(&l) > 0.5 && !has_kana(&l)) {
            let ph = placeholders
                .get(i % placeholders.len().max(1))
                .cloned()
                .unwrap_or_else(|| "（歌詞）".to_string());
            out.push(ph);
        } else {
            out.push(l);
        }
    }
    out
}

fn has_non_latin_letter(s: &str) -> bool {
    s.chars().any(|c| {
        matches!(c,
            '\u{0370}'..='\u{03ff}' | '\u{0400}'..='\u{052f}' | '\u{0590}'..='\u{05ff}' |
            '\u{0600}'..='\u{06ff}' | '\u{0900}'..='\u{097f}' | '\u{0e00}'..='\u{0e7f}' |
            '\u{3040}'..='\u{309f}' | '\u{30a0}'..='\u{30ff}' | '\u{3400}'..='\u{4dbf}' |
            '\u{4e00}'..='\u{9fff}' | '\u{ac00}'..='\u{d7af}')
    })
}

/// Target-script guard: latin targets reject any non-latin letter;
/// Japanese rejects only fully-alien lines.
pub fn wrong_script(line: &str, target_lang_name: &str) -> bool {
    if line.is_empty() {
        return false;
    }
    if target_lang_name == "Japanese" {
        let has_cjk = line.chars().any(crate::lang::is_cjk);
        let has_latin = line.chars().any(|c| c.is_ascii_alphabetic());
        return !has_cjk && !has_latin && has_non_latin_letter(line);
    }
    has_non_latin_letter(line)
}

/// Extract the JSON array from a chat reply that may carry prose fences.
pub fn extract_json_array(raw: &str) -> Option<Vec<String>> {
    if raw.is_empty() {
        return None;
    }
    let s = raw.trim();
    let i = s.find('[')?;
    let j = s.rfind(']')?;
    if j <= i {
        return None;
    }
    let cand = &s[i..=j];
    if let Ok(Value::Array(arr)) = serde_json::from_str::<serde_json::Value>(cand) {
        return Some(
            arr.into_iter()
                .map(|v| match v {
                    serde_json::Value::String(s) => s,
                    other => other.to_string().trim_matches('"').to_string(),
                })
                .collect(),
        );
    }
    None
}

use serde_json::Value;

pub fn has_ai_marker_text(text: &str) -> bool {
    text.contains("AI-generated by ASRSub")
}

/// Drop cues carrying the AI provenance marker (ladder sources must never
/// translate the marker itself).
pub fn strip_marker(cues: Vec<Cue>) -> Vec<Cue> {
    cues.into_iter()
        .filter(|c| !has_ai_marker_text(&c.text))
        .collect()
}

/// Re-time translated lines onto source cue timings (zip by position).
pub fn retime(cues: &[Cue], texts: &[String]) -> Vec<Cue> {
    cues.iter()
        .zip(texts.iter())
        .map(|(c, t)| Cue::new(c.start_ms, c.end_ms, t.clone()))
        .collect()
}

/// One-line truncation for error/log messages (multibyte-safe: chars, not
/// bytes). Shared by the LLM/Whisper/Jimaku error paths.
pub fn snippet(s: &str) -> String {
    s.chars().take(200).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_basic_srt() {
        let cues = parse_srt(
            "1\n00:00:01,000 --> 00:00:02,000\nHello\n\n2\n00:00:03,000 --> 00:00:04,000\nWorld\n",
        );
        assert_eq!(cues.len(), 2);
        assert_eq!(cues[0].start_ms, 1000);
        assert_eq!(cues[1].text, "World");
    }

    #[test]
    fn marker_bumps_before_early_dialogue() {
        let cues = vec![Cue::new(500, 1200, "hi")];
        let s = write_srt(&cues, true, 1500);
        assert!(s.contains(AI_MARKER));
        assert!(s.contains("00:00:00,000 --> 00:00:00,499"));
    }

    #[test]
    fn contiguous_clamp() {
        let mut cues = vec![Cue::new(0, 2000, "a"), Cue::new(1500, 3000, "b")];
        ensure_contiguous(&mut cues);
        assert_eq!(cues[1].start_ms, 2000);
    }

    #[test]
    fn cps_merge_chains_fast_cue() {
        let cues = vec![
            Cue::new(0, 1000, "this is a very long translated line indeed"),
            Cue::new(1100, 4000, "ok"),
        ];
        let merged = cps_merge(cues, 20.0, 84, 7000, 1000);
        assert_eq!(merged.len(), 1);
    }

    #[test]
    fn extracts_json_array_with_fences() {
        let raw = "Sure:\n```json\n[\"a\", \"b\"]\n```";
        assert_eq!(extract_json_array(raw).unwrap(), vec!["a", "b"]);
    }

    #[test]
    fn sanitize_collapses_screams() {
        let out = sanitize_lines(vec!["a".repeat(25)], 10);
        assert!(out[0].ends_with('…'));
        assert_eq!(out[0].chars().count(), 11);
    }

    #[test]
    fn marker_never_zero_duration() {
        // Dialogue at t=0 leaves no room: the marker takes a nominal 1 ms
        // instead of a zero-duration cue.
        let cues = vec![Cue::new(0, 900, "ohayou")];
        let s = write_srt(&cues, true, 1500);
        assert!(s.contains("00:00:00,000 --> 00:00:00,001"));
        assert!(validate_timeline(&parse_srt(&s), 8000, None).is_empty());
    }

    #[test]
    fn splits_long_cjk_cue_into_bounded_pieces() {
        let text: String = "あ".repeat(120);
        let cues = split_long_cues(vec![Cue::new(0, 24000, text)], 8000);
        assert!(cues.len() >= 3, "got {} pieces", cues.len());
        for c in &cues {
            assert!(c.end_ms - c.start_ms <= 8000, "piece too long: {c:?}");
        }
        for w in cues.windows(2) {
            assert!(w[1].start_ms >= w[0].start_ms);
            assert!(w[1].end_ms >= w[1].start_ms);
        }
        assert_eq!(cues.last().unwrap().end_ms, 24000);
    }

    #[test]
    fn marker_text_detection() {
        assert!(has_ai_marker_text("[AI-generated by ASRSub]"));
        assert!(!has_ai_marker_text("konnichiwa"));
    }

    // File-level gate corpus, ported from test_timeline_gate.py (the
    // production DP S01E09 backup case is host-local; the synthetic
    // pileup case below reproduces its signature).
    fn gate_cues(pairs: &[(f64, f64)]) -> Vec<Cue> {
        pairs
            .iter()
            .map(|(a, b)| Cue::new((a * 1000.0) as u32, (b * 1000.0) as u32, "テスト字幕"))
            .collect()
    }

    fn gate_seq(n: usize, step: f64, len: f64) -> Vec<(f64, f64)> {
        (1..=n)
            .map(|i| (i as f64 * step, i as f64 * step + len))
            .collect()
    }

    #[test]
    fn gate_healthy_passes_with_and_without_duration() {
        let cues = gate_cues(&gate_seq(59, 4.0, 3.0));
        assert_eq!(
            validate_timeline(&cues, 8000, Some(240.0)),
            Vec::<String>::new()
        );
        assert_eq!(validate_timeline(&cues, 8000, None), Vec::<String>::new());
    }

    #[test]
    fn gate_pileup_rejected_two_shared_allowed() {
        // DP S01E09 signature: 9 cues sharing one start after a long run.
        let mut pairs = gate_seq(99, 4.0, 3.0);
        pairs.extend([(986.1, 988.0); 9]);
        pairs.extend([(1200.0, 1203.0), (1250.0, 1253.0)]);
        let v = validate_timeline(&gate_cues(&pairs), 8000, Some(1469.7));
        assert!(v.iter().any(|s| s.contains("pileup")), "{v:?}");
        // Two simultaneous speaker cues are normal dialogue, not a pileup.
        // (Validated post-clamp, mirroring production order: the clamp
        // serializes the shared start; the gate must stay silent after.)
        let mut pairs = gate_seq(79, 5.0, 2.0);
        pairs.insert(30, (150.0, 152.0));
        let mut cues = gate_cues(&pairs);
        ensure_contiguous(&mut cues);
        assert_eq!(
            validate_timeline(&cues, 8000, Some(400.0)),
            Vec::<String>::new()
        );
    }

    #[test]
    fn gate_internal_hole_rejected() {
        // 504 s hole on a 900 s video (56% > 30%): a vanished dialogue block.
        let mut pairs = gate_seq(49, 4.0, 3.0);
        pairs.extend((0..50).map(|i| (700.0 + i as f64 * 4.0, 703.0 + i as f64 * 4.0)));
        let v = validate_timeline(&gate_cues(&pairs), 8000, Some(900.0));
        assert!(v.iter().any(|s| s.contains("gap")), "{v:?}");
    }

    #[test]
    fn gate_coverage_shrink_rejected() {
        // Subs end at ~40% of the video: collapsed-retime signature.
        let cues = gate_cues(&gate_seq(99, 4.0, 3.0));
        let v = validate_timeline(&cues, 8000, Some(1000.0));
        assert!(v.iter().any(|s| s.contains("coverage")), "{v:?}");
    }

    #[test]
    fn gate_monotonicity_enforced() {
        // Production clamps (and sorts) before validating, so this guards
        // the predicate itself: a reordered timeline must name monotonicity.
        let cues = gate_cues(&[(10.0, 12.0), (5.0, 6.0), (20.0, 22.0)]);
        let v = validate_timeline(&cues, 8000, None);
        assert!(v.iter().any(|s| s.contains("monotonic")), "{v:?}");
    }
}
